/*
 Navicat Premium Data Transfer

 Source Server         : 本地
 Source Server Type    : MySQL
 Source Server Version : 80027
 Source Host           : localhost:3306
 Source Schema         : trader

 Target Server Type    : MySQL
 Target Server Version : 80027
 File Encoding         : 65001

 Date: 25/08/2022 21:00:56
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for coin_dev_member
-- ----------------------------
DROP TABLE IF EXISTS `coin_dev_member`;
CREATE TABLE `coin_dev_member`  (
  `id` int(0) NOT NULL AUTO_INCREMENT,
  `code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `headimg` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `twitterlink` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `linkinLink` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `isfounder` int(0) NOT NULL,
  `description` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 667 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin ROW_FORMAT = Compact;

-- ----------------------------
-- Records of coin_dev_member
-- ----------------------------
INSERT INTO `coin_dev_member` VALUES (694, 'bitcoin', '中本聪', '创始人', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (695, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (696, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (697, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (698, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (699, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (700, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (701, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', 0, '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n');
INSERT INTO `coin_dev_member` VALUES (702, 'ethereum', 'Gavin Wood', '创始人兼首席技术官', 'https://s2.gongft.com/image/20190621/4731561099774617.png', 'https://twitter.com/gavofyork', 'https://www.linkedin.com/in/gavin-wood-88843316/', 0, '');
INSERT INTO `coin_dev_member` VALUES (703, 'ethereum', 'Jeffrey Wilcke', '创始人和Go-Ethereum领导', 'https://s2.gongft.com/image/20190621/8231561099283368.png', 'https://twitter.com/jeffehh', 'https://www.linkedin.com/in/jeffreywilcke', 0, '<p>Jeffrey Wilcke是以太坊的创始人之一。他于2013年开始使用Go编程语言首次实现以太坊，并一直担任Go团队负责人和首席开发人员。Go客户端于2015年7月30日成功推出，标志着创世块和以太坊平台的发布。</p>\n');
INSERT INTO `coin_dev_member` VALUES (704, 'ethereum', 'Anthony Di lorio', '创始人', 'https://s2.gongft.com/image/20190621/2281561099563578.png', 'https://twitter.com/diiorioanthony', 'https://www.linkedin.com/in/anthonydiiorio1/', 0, '');
INSERT INTO `coin_dev_member` VALUES (705, 'ethereum', 'Joseph Lubin', '创始人', 'https://s2.gongft.com/image/20190621/7931561098887167.png', 'https://twitter.com/ethereumjoseph', 'https://www.linkedin.com/in/joseph-lubin-48406489', 0, '<p>Joseph Lubin，就职于ConsenSys，现任创始人一职。作为行业享有盛名的大咖，Joseph Lubin行事低调，对工作热情饱满，多次受邀作为嘉宾出席各类大会，并发表了精彩演讲。<br />\n2016年09月19日，Joseph Lubin受邀参加了由以太坊基金会在虹口区黄浦路199号主办的《2016上海区块链国际周(Shanghai International Blockchain Week)》，并发表了精彩演讲。</p>\n');
INSERT INTO `coin_dev_member` VALUES (706, 'ethereum', 'Vlad Zamfir', '以太坊开发团队的核心成员。', 'https://s2.gongft.com/images/baike/7c972b50029c452c747c8ff805e8cb1c.jpg', 'https://twitter.com/vladzamfir', 'https://www.linkedin.com/in/vlad-zamfir/', 0, '<p>Vlad Zamfir 是以太坊开发团队的核心成员，也是博雅公关公司的数据分析顾问。他积极参与以太坊社区，工作主要聚焦于以太坊生态中的「加密经济学」、PoS 股权证明、Sharding 分片等。</p>\n\n<p>自 2014 年以来，Vlad Zamfir 一直是以太坊基金会的研究员，他是 Casper 协议升级的首席开发者。</p>\n');
INSERT INTO `coin_dev_member` VALUES (707, 'ethereum', 'Mihai Alisie', '以太坊、Bitcoin Magazine 联合创始人。', 'https://s2.gongft.com/images/baike/8e6708fd017360dc61c2dacf0eaebb27.jpg', 'https://twitter.com/MihaiAlisie', 'https://www.linkedin.com/in/mihaialisie/', 0, '<p>Mihai Alisie 是以太坊、Bitcoin Magazine 的联合创始人，目前专注于使 Akasha 项目的梦想成为现实。他自 2011 年以来一直积极参与区块链技术，当时，他与 Vitalik Buterin 共同创建了世界上首个以比特币为中心的出版物 Bitcoin Magazine，由他担任该杂志的主编，直至 2013 年底，他也加入 Vitalik 创立的以太坊项目。</p>\n\n<p>在以太坊的早期，Mihai Alisie 领导瑞士创建对以太坊众筹活动至关重要的商业基础设施和法律框架。此后，他监督了以太坊的战略，和以太坊基金会副主席的工作。直到 2015 年底，他将注意力转向 AKASHA 项目。</p>\n');
INSERT INTO `coin_dev_member` VALUES (708, 'ethereum', 'Gustav Simonsson', '以太坊的核心开发者之一。', 'https://s2.gongft.com/images/baike/2a688fea428828654e6e19a11df10b7c.jpg', 'https://twitter.com/classygustav', '', 0, '<p>Gustav Simonsson 为以太坊的核心开发者，具体工作涉及共识协议、核心客户端和网络安全方面，专注于以太坊区块链的安全性、Golang 客户端，确保平台的安全性。</p>\n\n<p>他拥有计算机科学背景，自 2011 年以来一直致力于开发复杂的后端系统，并在金融科技、支付处理、电信与区块链系统上积累经验。</p>\n');
INSERT INTO `coin_dev_member` VALUES (709, 'ethereum', 'Lane Rettig', '以太坊 Ewasm 独立开发者。', 'https://s2.gongft.com/images/baike/3746edc0a3deab4ab806b0e561783ae1.jpg', 'https://twitter.com/lrettig', '', 0, '\n                            <p>Lane Rettig 是独立的以太坊核心开发者，也是 Ewasm 团队的成员之一，专注于为以太坊 2.0、分片等相关工作。他主要从事有关用户及开发者的体验设计、治理和社交可扩展性的独立研究。</p>\n<p>另外，他是纽约曼哈顿的加密社区 Crypto NYC 的创始人，致力于使所有人都能使用 Web 3.0 与区块链技术。他是黑客、马拉松跑者、冒险家与企业家、经济学家、思想家、作家，掌握多门语言，还是沃顿商学院 MBA 学生。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (710, 'ethereum', 'Hudson Jameson', '以太坊开发者，专注于 Solidity 编程语言。', 'https://s2.gongft.com/images/baike/93fbe60c9375abf3057fb1a577ef2dab.jpg', 'https://twitter.com/hudsonjameson', 'https://www.linkedin.com/in/hudsonjameson/', 0, '\n                            <p>以太坊开发者，专注于 Solidity 编程语言，工作在 Oaken Innovations 与以太坊基金会。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (711, 'ethereum', 'Martin Holst Swende', '以太坊安全主管。', 'https://s2.gongft.com/images/baike/72581667eb490c51dcba1c3f7f423b5e.jpg', 'https://twitter.com/mhswende', 'https://www.linkedin.com/in/martin-holst-swende-a6664/', 0, '<p>Martin Holst Swende，以太坊基金会安全部门主管。</p>');
INSERT INTO `coin_dev_member` VALUES (712, 'ethereum', 'Jake Lang', '在以太坊核心开发与研究者，主要从事 Ewasm 开发。', 'https://s2.gongft.com/images/baike/ee7e3b8a5fbe25a315d95f845f929715.jpg', 'https://twitter.com/jake_theripper', 'https://www.linkedin.com/in/jak3lang/', 0, '\n                            <p>Jake Lang 在以太坊，从事 Ewasm 开发，也在 etclabscore 上使用 SputnikVM JIT，亦是 Wasm-chisel 共同维护者。 他对 Rust、WebAssembly、OSDev 以及加密的所有东西都感兴趣。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (713, 'ethereum', 'Alex Beregszaszi', '以太坊开发者。', 'https://s2.gongft.com/images/baike/f927a441b4e168b7d9a80ed6378aa382.jpg', 'https://twitter.com/alexberegszaszi', 'http://ie.linkedin.com/in/alexberegszaszi', 0, '\n                            <p>以太坊开发者，常出现在都柏林、柏林以及区块链上。更具体地说，是出现在 Solidity 与 Ewasm 上。懒得发推特，更多在 Github 上。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (714, 'ethereum', 'Mister Ligi', '以太坊开发者。', 'https://s2.gongft.com/images/baike/967645ff1234359058c78e2da35e2194.jpg', 'https://twitter.com/mr_ligi', '', 0, '\n                            <p>Mister Ligi 是以太坊开发者。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (715, 'ethereum', 'Aya Miyaguchi', '以太坊基金会执行总监。', 'https://s2.gongft.com/images/baike/7b60ede6e6ee89fa9a9d4bded68bcafe.jpg', 'https://twitter.com/mi_ayako', 'https://www.linkedin.com/in/amiyaguchi/', 0, '\n                            <p>Aya Miyaguchi 目前是以太坊基金会执行总监，曾在 Kraken 交易平台全权负责日本地区的运营工作。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (716, 'ethereum', 'Joey Zhou', '以太坊开发的鼻祖级人物。', 'https://s2.gongft.com/images/baike/c77980f9b5e0396f418985756ab87902.jpg', 'https://twitter.com/josephzhou', 'https://www.linkedin.com/in/josephyzhou/', 0, '\n                            <p>Joey Zhou 是以太坊开发的鼻祖级人物，早在 2014 年，编写了以太坊上的首个节点实现，并为 Geth、Go-Ethereum、CPP-Ethereum 协议的开发做出了重要贡献。另外，他是 Cyborgenic 咨询公司的管理合伙人，专注于金融科技创新，亦是一位活跃的天使投资人和创业顾问。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (717, 'ethereum', 'Péter Szilágyi', '以太坊核心开发者。', 'https://s2.gongft.com/images/baike/78964ccd6dfea14bf93ba0bb85593659.jpg', 'https://twitter.com/peter_szilagyi', 'https://www.linkedin.com/in/karalabe/', 0, '\n                            <p>Péter Szilágyi，代号 Karalabe，以太坊的核心开发者，另外，他也是分布式通讯应用 Project Iris 的作者、RegionRank 创始人、Ether API 共同创建者。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (718, 'ethereum', 'Greg Colvin', '号称「以太坊甘道夫」。', 'https://s2.gongft.com/images/baike/d4992988ae2587bab1fdac0a1c972396.jpg', 'https://twitter.com/greg_colvin', 'https://www.linkedin.com/in/gregcolvin/', 0, '\n                            <p>「以太坊甘道夫」之称的工程师 Greg Colvin，现为 Algorand 项目理论团队成员，凭借三十多年的计算机软件研发经验，帮助项目创建原子交换、智能合约、虚拟机等。Colvin 拥有康奈尔大学的定量心理学博士学位，以及科罗拉多大学心理学和计算机科学学士学位，并在 ANSI/ISO c++标准委员会任职多年，在企业软件开发公司甲骨文是负责创建 Oracle Java 虚拟机的团队的主要成员，最近参与了以太坊虚拟机性能的改进，并致力于提高以太坊生态系统中流程的透明度。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (719, 'ethereum', 'Fabian Vogelsteller', 'LUKSO 创始人，以太坊项目从事 Ðapp 开发。', 'https://s2.gongft.com/images/baike/aca18a88aa777d83bbe989adc84daa59.jpg', 'https://twitter.com/feindura', 'https://www.linkedin.com/in/fabian-vogelsteller-46365042/', 0, '<p>Fabian Vogelsteller 是 LUKSO 创始人、作者，从前在 Mist、Web3.js 以及以太坊项目从事 &ETH;app 开发。</p>\n');
INSERT INTO `coin_dev_member` VALUES (720, 'ethereum', 'Raul Jordan', 'Prysmatic Labs 联合创始人，以太坊开发者。', 'https://s2.gongft.com/images/baike/aaaa000ca9c606014b15771281620c77.jpg', 'https://twitter.com/raulitojordan', '', 0, '<p>Raul Jordan 是 Prysmatic Labs 联合创始人，也兼任 zk Capital 合伙人，毕业于哈佛，区块链工程师、以太坊开发者，专注于 Prysmatic Labs 分片技术开发。</p>\n');
INSERT INTO `coin_dev_member` VALUES (721, 'ethereum', '平井洋一', '以太坊形式化验证工程师，负责虚拟机项目。', 'https://s2.gongft.com/images/baike/f9e61c8ac1daf0e7c646b43cb5ebffae.jpg', 'https://twitter.com/pirapira', '', 0, '\n                            <p>以太坊形式化验证工程师，负责虚拟机项目。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (722, 'ethereum', 'Justin Drake', '以太坊的研究分析师。', 'https://s2.gongft.com/images/baike/26ab39cb5a23b8dc2dfc9a0384da8157.jpg', 'https://twitter.com/drakefjustin', 'https://www.linkedin.com/in/drakefjustin', 0, '\n                            <p>Justin Drake 住在英国剑桥，拥有英国剑桥大学数学系学士和硕士学位。他于 2013 年创立了剑桥比特币聚会小组，并于 2014 年离开了他作为程序员、FPGA 工程师的职位，专心研究区块链领域。2015 年，他运营了比特币 ATM，并成立了 Duo Money，一家为 OpenBazaar 提供网络界面的公司。而现在，他是以太坊基金会的研究分析师，专注于分片。</p>\n<p>他在 18 岁之后定居英国剑桥，是法国人也是意大利人，妻子是俄罗斯人。父亲是一名工程师，英国人，而母亲是一名心理师，阿根廷人。可见 Justin Drake 的成长背景与生活经验十分国际化，自幼在法国长大，中学时期在中国，此后在英国。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (723, 'ethereum', 'Karl Floersch', '以太坊核心开发者。', 'https://s2.gongft.com/images/baike/7240a3cf09c18ab2ac8e145d70f59a7d.jpg', 'https://twitter.com/karl_dot_tech', 'https://www.linkedin.com/in/karlfloersch', 0, '\n                            <p>以太坊核心开发者，年仅 23 岁，主要参与开发以太坊 Casper 以及权益证明机制 PoS 运算法则。除研究 Casper 以外，他爱好冥想和即兴饶舌，从小受到印度教的熏陶，通过冥想来思考和感悟一些事情，用饶舌表达自己当下的感受。</p>\n<p>Casper 的设计理念最初源于 Vitalik、Vlad 及其他研究者的讨论，已经归纳出的核心原则包括：关键的经济因素、必要的稳健性、普通用户的优先原则。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (739, 'tether', 'Craig Sellars', '创始人兼顾问', 'https://s2.gongft.com/image/20190622/8151561175194467.png', '', 'https://www.linkedin.com/in/craigcsellars/', 0, '');
INSERT INTO `coin_dev_member` VALUES (740, 'tether', ' JL Van Der Velde', '首席执行官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (741, 'tether', 'Giancarlo Devasini', '首席财务官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (742, 'tether', 'Phil Potter', 'Bitfinex 与 Tether 首席战略官。', 'https://s2.gongft.com/images/baike/612647c31b17f1e13bd19ee9f9508d37.jpg', '', 'https://www.linkedin.com/in/phil-potter-0b6756154/', 0, '\n                            <p>Phil Potter 自 1994 年毕业于耶鲁大学，曾经是摩根士丹利的衍生品交易分析师，而后开发自动化投资组合管理技术，在贝尔斯登工作两年以后，他参与创办 Mercury Securities, LLC，担任首席技术官，而后共同创立了 PacMid Technologies、Dimension Capital 等，专注于开发和实施尖端交易技术以及创建成功的自动交易咨询业务。</p>\n<p>2013 年起，他开始涉足比特币相关的项目，起初作为 Bitfinex 大客户做加密货币基金管理，后被说服于 2013 年底加入 Bitfinex，担任首席战略官。同时，他参与开发了 Tether，也担任首席战略官。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (743, 'tether', 'Matthew Tremblay', '首席合规官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (744, 'tether', 'Craig Sellars', '创始人兼顾问', 'https://s2.gongft.com/image/20190622/8151561175194467.png', '', 'https://www.linkedin.com/in/craigcsellars/', 0, '');
INSERT INTO `coin_dev_member` VALUES (745, 'tether', ' JL Van Der Velde', '首席执行官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (746, 'tether', 'Giancarlo Devasini', '首席财务官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (747, 'tether', 'Phil Potter', 'Bitfinex 与 Tether 首席战略官。', 'https://s2.gongft.com/images/baike/612647c31b17f1e13bd19ee9f9508d37.jpg', '', 'https://www.linkedin.com/in/phil-potter-0b6756154/', 0, '\n                            <p>Phil Potter 自 1994 年毕业于耶鲁大学，曾经是摩根士丹利的衍生品交易分析师，而后开发自动化投资组合管理技术，在贝尔斯登工作两年以后，他参与创办 Mercury Securities, LLC，担任首席技术官，而后共同创立了 PacMid Technologies、Dimension Capital 等，专注于开发和实施尖端交易技术以及创建成功的自动交易咨询业务。</p>\n<p>2013 年起，他开始涉足比特币相关的项目，起初作为 Bitfinex 大客户做加密货币基金管理，后被说服于 2013 年底加入 Bitfinex，担任首席战略官。同时，他参与开发了 Tether，也担任首席战略官。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (748, 'tether', 'Matthew Tremblay', '首席合规官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (749, 'binance-coin', 'Roger Wang', '联合创始人兼首席技术官', 'https://s2.gongft.com/image/20190622/6611561172069411.png', '', 'https://www.linkedin.com/in/rogerlilaiwang/', 0, '<p>Roger是联合创始人兼首席技术官。他在金融行业工作了10多年，负责组建技术团队。在BijieTech之前，Roger在日本最大的投资银行野村证券工作。他负责一个全球信用记录、分析和评分系统，该系统支持数千名全球交易员和分析师。他还成功地实现了一个智能债券匹配引擎。在野村证券(Nomura)之前，他是摩根士丹利(Morgan Stanley)的一名技术领导者。在摩根士丹利，他设计并构建了一个金融TB级别的数据仓库，支持大量用户进行实时数据分析和金融建模。他还是低延迟算法交易系统的核心开发人员，该系统为该公司最大的客户提供服务，如百仕通(Blackstone)和惠灵顿基金(Wellington Fund)，为该公司带来了可观的佣金收入。</p>\n');
INSERT INTO `coin_dev_member` VALUES (750, 'binance-coin', 'James Hofbauer', '首席架构师', 'https://s2.gongft.com/image/20190622/6611561173101862.png', '', 'https://www.linkedin.com/in/jamesjhofbauer/', 0, '<p>詹姆斯（James）在美国长大并接受教育，以优异成绩获得计算机科学学士学位。他精通两种语言，英语为母语，日语流利<br />\n他设计并实现了核心匹配引擎及其中间件。他还负责监管客户端交易所的公共端点，以确保安全性和高性能。在BijieTech之前，James就职于硅谷一家专注于大数据分析的公司Palantir。在Palantir之前，James在Fusion Systems工作。James参与的一个著名项目是一家全球投资银行的系统架构重新设计，重点是减少系统数量，加密和安全地处理敏感数据，并引入了一个新的用户安全系统。</p>\n');
INSERT INTO `coin_dev_member` VALUES (751, 'binance-coin', 'Paul Jankunas', '工程副总裁', 'https://s2.gongft.com/image/20190622/6701561173659274.png', '', 'https://www.linkedin.com/in/paul-jankunas-4ba9513/', 0, '<p>Paul是BijieTech的工程副总裁，负责核心机器引擎的c++实现。他拥有超过15年开发外汇系统和金融交易应用程序的经验。在BijieTech之前，Paul在东京SBI集团的SBI BITS工作。SBI集团是一家上市金融服务公司，业务范围广泛。Paul负责交易应用程序的客户端和服务器端开发。在此之前，Paul曾在东京的fsystems工作，担任猛禽(Raptor)的开发主管。猛禽是一种延迟小于2微秒的市场门户，此前他在纽约为彭博社(Bloomberg)工作。</p>\n');
INSERT INTO `coin_dev_member` VALUES (752, 'binance-coin', 'Allan Yan', '产品总监', 'https://s2.gongft.com/image/20190622/5121561174220099.png', '', 'https://www.linkedin.com/in/allannyan/', 0, '<p>Allan是BijieTech的联合创始人和产品总监。Allan拥有超过10年的产品设计、用户体验和贸易经验。他推动BijieTech建立的交换系统的创新，并推动产品在这个竞争激烈的领域远远领先于竞争对手。在BijieTech之前，Allan就职于东方国际控股有限公司，这是上海最大的进出口公司之一。负责ERP、e-Fax等多个信息化产品的实施。同时，他还领导了各种游戏和视频点播内容平台。</p>\n');
INSERT INTO `coin_dev_member` VALUES (753, 'binance-coin', 'Sunny Li', '运营总监', 'https://s2.gongft.com/image/20190622/4801561174521281.png', '', 'http://www.linkedin.com/in/SunnyJiachenLi', 0, '<p>Sunny是BijieTech的联合创始人和运营总监。他拥有多年的管理和技术咨询经验，领导过20多个交流系统项目，为战略、运营、风险控制和系统开发提供全面咨询。<br />\n在BijieTech之前，Sunny在埃森哲担任高级顾问。为多家世界500强企业提供战略咨询和IT咨询服务，主持多项物联网、大数据、ERP信息集成系统项目。</p>\n');
INSERT INTO `coin_dev_member` VALUES (754, 'ripple', 'Brad Garlinghouse', 'Ripple 首席执行官。', 'https://s2.gongft.com/images/baike/ec2586d02e1ebe75507644dbf0247150.jpg', 'https://twitter.com/bgarlinghouse', 'https://www.linkedin.com/in/bradgarlinghouse/', 0, '\n                            <p>Brad Garlinghouse 是 Ripple 首席执行官，也是董事会成员。在加入 Ripple 之前，他曾担任文件协作服务 Hightail 的首席执行官、美国在线 AOL 消费者应用总裁，以及在雅虎担任过多个行政职位。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (755, 'ripple', 'Ed Roman', 'Hack VC 管理合伙人。', 'https://s2.gongft.com/images/baike/e284298d4e00fc4854e53bf094ac2f18.jpg', 'https://twitter.com/ed_roman', 'https://www.linkedin.com/in/ed-roman-19686/', 0, '\n                            <p>Ed Roman 是 Hack VC 管理合伙人、企业家、开发者，以及天使投资人。他的专长是发展小企业，组建和领导团队取得成功。另外，他也是一位屡获殊荣的游戏开发者、畅销的技术书籍作者。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (756, 'ripple', 'Chris Larsen', 'Ripple 联合创始人、执行主席。', 'https://s2.gongft.com/images/baike/d3f70a3d03c7d7dd4be16536b4f01d89.jpg', 'https://twitter.com/chrislarsensf', 'https://www.linkedin.com/in/chris-larsen-7721772/', 0, '\n                            <p>Chris Larsen 是 Ripple 联合创始人兼执行主席，Ripple 是一家全球支付的企业区块链解决方案。他目前是数据科学公司 Distilled Analytics 的顾问。 在创立 Ripple 之前，他是 P2P 贷款服务公司 Prosper 的首席执行官，也是在线贷款服务公司 E-LOAN 的首席执行官。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (757, 'ripple', 'David Schwartz', '首席技术官', 'https://s2.gongft.com/image/20190621/9111561104168747.png', 'https://twitter.com/JoelKatz', 'https://www.linkedin.com/in/david-schwartz-8b767b34/', 0, '<p>David Schwartz是Ripple的首席技术官，是Ripple共识网络的原始架构师之一。在加入Ripple之前，David Schwartz是Santa Clara软件开发人员WebMaster Incorporated的首席技术官。他为CNN和国家安全局（NSA）等组织开发了加密云存储和企业消息系统。被称为&ldquo;JoelKatz&rdquo;，他是数字货币界的一位受人尊敬的代言人。</p>\n');
INSERT INTO `coin_dev_member` VALUES (758, 'ripple', 'Asheesh Birla', '产品副总裁', 'https://s2.gongft.com/image/20190621/2061561104435973.png', 'https://twitter.com/ashgoblue', 'https://www.linkedin.com/in/asheeshbirla/', 0, '<p>在2013年首次加入领导其产品套件的开发。Asheesh是区块链行业专家，是区块链和加密货币的撰稿人，演讲者和顾问。Asheesh 15年前在硅谷开始了他的企业家生涯，他在那里创立了一家内容管理公司，并于2005年将其出售给Thomson-Reuters，成为他们的全球技术副总裁。2010年离开Thomson-Reuters之后，Asheesh建议并在硅谷的一些初创公司领导产品设计。</p>\n');
INSERT INTO `coin_dev_member` VALUES (759, 'ripple', 'Patrick Griffin ', '业务发展高级副总裁', 'https://s2.gongft.com/image/20190621/5711561104782708.png', 'https://twitter.com/patgriffin9', 'https://www.linkedin.com/in/patrick-griffin-72b1255', 0, '<p>在加入Ripple之前是互联网支付和身份公司Jumio的早期雇员，负责构建业务开发团队和销售策略。</p>\n');
INSERT INTO `coin_dev_member` VALUES (760, 'ripple', 'Christopher Kanaan', '工程副总裁', 'https://s2.gongft.com/image/20190621/2731561104957226.png', '', 'https://www.linkedin.com/in/ckanaan/', 0, '');
INSERT INTO `coin_dev_member` VALUES (761, 'ripple', 'John Mitchell', '高级副总裁', 'https://s2.gongft.com/image/20190621/6591561105935820.png', '', 'https://www.linkedin.com/in/johnemitchell/', 0, '<p>Eric van Miltenburg是Ripple的业务运营高级副总裁。他在业务开发，战略规划，业务运营和企业发展方面拥有20年的领导经验。在加入Ripple之前，曾在高增长的初创企业和财富500强企业担任高级职位，包括Adobe，Yahoo！，Hightail，RedSwoosh，Work.com和Excite@Home.com。他以解决复杂业务问题和执行有助于技术公司加速增长战略的丰富经验而闻名。</p>\n');
INSERT INTO `coin_dev_member` VALUES (762, 'ripple', 'Brynly Llyr', '总法律顾问', 'https://s2.gongft.com/image/20190621/7391561105612855.png', '', 'https://www.linkedin.com/in/brynly-llyr-3075709/', 0, '<p>Brynly Llyr是Ripple的总法律顾问。在加入Ripple之前，为金融科技公司提供法律服务，并担任高级法律顾问职务，包括担任PayPal中小企业集团的法律总顾问以及eBay的诉讼高级总监。在这些职位上，她领导诉讼团队，就商业交易，并购和知识产权保护等问题开展合作。Brynly Llyr还曾在O&#39;Melveny＆Myers和Charles Schwab担任过职务，并在美国加利福尼亚州北区地方法院的Fern M. Smith（Ret。）法官下任职。</p>\n');
INSERT INTO `coin_dev_member` VALUES (763, 'ripple', 'Monica Long ', '营销副总裁', 'https://s2.gongft.com/image/20190621/3931561105806130.png', 'https://twitter.com/MonicaLongSF', 'https://www.linkedin.com/in/monicalong/', 0, '<p>onica Long是Ripple的市场营销和传播高级副总裁。在她的职业生涯中，帮助技术公司推动了金融业的根本变革。在加入Ripple之前，Monica Long曾在Intuit的企业传播部门工作。在此之前，她支持各种B2B和B2C领域的初创客户，其中有几家涉及金融科技方面，包括Prosper。</p>\n');
INSERT INTO `coin_dev_member` VALUES (764, 'ripple', 'Sandi Kochhar', '人力副总裁', 'https://s2.gongft.com/image/20190621/6571561105189610.png', '', 'https://www.linkedin.com/in/sandikochhar/', 0, '<p>在加入Ripple之前，她曾在AppDirect，Atlassian和SuccessFactors等企业软件公司担任多个领导职务。在每个角色中，她帮助公司扩展规模，领导全球扩张，并购整合以及与IPO相关的活动。</p>\n');
INSERT INTO `coin_dev_member` VALUES (765, 'ripple', 'Catherine Coley', '在 Ripple 负责 XRP 机构流动性的主管。', 'https://s2.gongft.com/images/baike/8a807eac7bae786aeee73be864dffccd.jpg', 'https://twitter.com/cryptocoley', 'https://www.linkedin.com/in/catherinegcoley/', 0, '\n                            <p>Catherine Coley 在 Ripple 主管 XRP 机构流动性，此前，她在硅谷银行为初创企业的全球支付与战略扩张提供建议，以前她也有与摩根士丹利的香港、伦敦分部进行外汇交易市场的经验，与全球对冲基金和资产管理公司密切合作。她是香港中文大学、哥本哈根商学院、北卡罗来纳 Kenan Flagler 商学院的全球学者。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (766, 'cardano', 'Charles Hoskinson', '创始人', 'https://s2.gongft.com/image/20190622/2981561188085146.png', 'https://twitter.com/IOHK_Charles', 'https://www.linkedin.com/in/charles-hoskinson-1a95a4b4/', 0, '<p>查尔斯&middot;霍金森(Charles Hoskinson)是科罗拉多州的一位科技企业家、数学家和区块链爱好者。他主要以创造Cardano而闻名。<br />\n霍金森的专业经验包括创建三家与加密货币相关的初创企业:Invictus Innovations、Ethereum和IOHK。他还是比特币基金会教育委员会的创始主席，并于2013年9月成立了加密货币研究小组。<br />\n他目前的项目集中在加密货币主题的教育、分散化的福音传播和使主流更容易使用加密工具。</p>\n');
INSERT INTO `coin_dev_member` VALUES (767, 'cardano', 'Jeremy Wood', '创始人', 'https://s2.gongft.com/image/20190622/0491561188615908.png', 'https://twitter.com/iohk_jeremy', 'https://jp.linkedin.com/in/jeremykwood', 0, '');
INSERT INTO `coin_dev_member` VALUES (768, 'cardano', 'Eileen Fitzgerald', '执行副总裁 计划负责人、COO', 'https://s2.gongft.com/image/20190622/0001561188879628.png', 'https://twitter.com/EileenFitzy', 'https://www.linkedin.com/in/eifitzgerald/', 0, '');
INSERT INTO `coin_dev_member` VALUES (769, 'cardano', 'Domen Kožar', 'CTO', '', '', 'https://www.linkedin.com/in/domen-ko%C5%BEar-b753779', 0, '');
INSERT INTO `coin_dev_member` VALUES (770, 'solana', 'Anatoly Yakovenko', 'CEO', 'https://s2.gongft.com/images/baike/4E04CEDF5E46EFBF5AAB09965FAEE905.png?v=1592812802', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (771, 'solana', 'Greg Fitzgerald', 'CTO', 'https://s2.gongft.com/images/baike/71334DBF0ED45DE1658BD33A49C7A2DD.png?v=1592812867', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (772, 'solana', 'Raj Gokal', 'COO', 'https://s2.gongft.com/images/baike/D55E383950875380247BEECC1E7DCC62.png?v=1592812957', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (773, 'dogecoin', 'Jackson Palmer', '狗币创始人。', 'https://s2.gongft.com/images/baike/5c99f3816ea4eab8415c5b5a23808a94.jpg', 'https://twitter.com/ummjackson', 'https://www.linkedin.com/in/jacksonpalmer/', 0, '\n                            <p>狗币创始人，也是 Adobe 高级经理。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (774, 'shibainu', 'Ryoshi', 'SHIB 和 LEASH 创始人', 'https://s2.gongft.com/images/baike/56001D79B34A146CF666CBD86DDCC91B.png?v=1620463765', 'https://twitter.com/RyoshiResearch', '', 0, '<p>加密货币独立交易员，热衷于去中心化组织的建设与发展。</p>\n');
INSERT INTO `coin_dev_member` VALUES (775, 'dai', 'Rune Christensen', '联合创始人兼首席执行官', 'https://s2.gongft.com/images/baike/4996256b09df187c28d75021f1e5aea5.jpg', 'https://twitter.com/runekek', 'https://www.linkedin.com/in/rune-christensen-5b5220ab/', 0, '<p>Rune Christensen是MakerDAO联合创始人兼首席执行官。由MakerDAO发布的 DAI，是世界上首个在以太坊区块链上使用的稳定币，旨在透过应对市场变化的智能合约系统去除价格波动。他自2015年以来，一直致力于建立分布式自治组织的愿景，以及稳定数字货币的经济基础。此前，他曾参与创办Try China国际招聘公司。</p>\n');
INSERT INTO `coin_dev_member` VALUES (776, 'dai', 'Andy Milenius', '首席技术官', 'https://s2.gongft.com/images/baike/fa22646b47953682b7e0839bbf1494a3.jpg', 'https://twitter.com/RealZandy', 'https://www.linkedin.com/in/andy-milenius-919922123/', 0, '<p>Andy Milenius是MakerDAO首席技术官，对于分布是自治组织及分散治理和引导在线社区的机制设计特别感兴趣。此前，他在Amazon Web Services工作，拥有密歇根大学的计算机科学学位，出生在美国底特律。</p>\n');
INSERT INTO `coin_dev_member` VALUES (777, 'tron', '孙宇晨', '创始人', 'https://s2.gongft.com/images/baike/6dbe4bcca862cd26ec6746ed0ca19334.png', 'https://twitter.com/justinsuntron', 'https://www.linkedin.com/in/justinsuntron/', 0, '<p>美国常青藤盟校宾夕法尼亚大学硕士，北京大学学士。前Ripple大中华区首席代表，移动社交应用陪我APP创始人兼CEO，锐波创始人兼CEO，《财富自由革命之路》发起人，波场TRON基金会创始人。</p>\n');
INSERT INTO `coin_dev_member` VALUES (778, 'uniswap', 'Noah Zinsmeister', 'Uniswap 资深开发工程师', 'https://s2.gongft.com/images/baike/CBCDB81FD1888F2C66BC083079898AE5.png?v=1605517801', 'https://twitter.com/NoahZinsmeister', '', 0, '<p>Noah Zinsmeister 是 Uniswap 资深开发工程师，也是 Web3-react 创建者，以太坊 ERC-1484 的共同作者。</p>\n\n<p>他于 2016 年毕业于哥伦比亚大学的经济学与数学专业，毕业后，在纽约联邦储备银行工作了近两年，担任货币与支付研究部门的高级研究分析师。因为对加密货币的长期兴趣，最终促使他去 Hydrogen 工作，编写安全级智能合约，并参与撰写了 ERC-1484 数字身份协议，以及开源的区块链工具等。现在，他是 Uniswap 资深开发工程师。</p>\n');
INSERT INTO `coin_dev_member` VALUES (779, 'uniswap', 'Ashleigh Schap', 'Uniswap 顾问', 'https://s2.gongft.com/images/baike/5D66C82DF45487750CB880AA23AA7825.png?v=1605517876', 'https://twitter.com/ashleighschap', '', 0, '<p>Ashleigh Schap 是 Uniswap 顾问，此前在 MakerDAO 负责商务拓展。</p>\n');
INSERT INTO `coin_dev_member` VALUES (780, 'uniswap', 'Ian Lapham', 'Uniswap 开发工程师', 'https://s2.gongft.com/images/baike/0C33BCF015A9566CBAB423602A95DC26.png?v=1605517928', 'https://twitter.com/ianlapham', '', 0, '<p>Ian Lapham 是 Uniswap 开发工程师，同时也在 John Hancock 从事区块链开发。</p>\n');
INSERT INTO `coin_dev_member` VALUES (781, 'uniswap', 'Michael Demarais', 'Rainbow 联合创始人', 'https://s2.gongft.com/images/baike/C9C805BE3FABFC27A288E140D60F4ADF.png?v=1605517981', 'https://twitter.com/mikedemarais', '', 0, '<p>Mike Demarais 是 Rainbow 联合创始人，也参与 UniSwap 交易平台，从前在 Balance.io 担任开发工程师，是对于界面极其痴迷。</p>\n');
INSERT INTO `coin_dev_member` VALUES (782, 'uniswap', 'Caleb Sheridan', 'Blocklytics 联合创始人', 'https://s2.gongft.com/images/baike/275B555AFD722EFA05698F2E19061300.png?v=1605518207', 'https://twitter.com/calebsheridan', '', 0, '<p>Caleb Sheridan 是 Blocklytics 联合创始人。此前，他是 PokerStars 产品负责人，在 2019 年 1 月参与创办 Blocklytics，帮助加密货币和区块链团队获得数据。他擅长于使用数据设计、管理、增加业务，从点对点的游戏到加密经济系统的相关经验。</p>\n');
INSERT INTO `coin_dev_member` VALUES (783, 'uniswap', 'Callil Capuozzo', 'Uniswap 设计师', 'https://s2.gongft.com/images/baike/23381CB95521C7BBCCC7EA4E502CCBFA.png?v=1605518261', 'https://twitter.com/_callil', '', 0, '<p>Callil Capuozzo 是 Hayden Adams 从小学到高中的一个朋友，一直在微软、谷歌担任设计师，此后在 FOAM 网站上钻研以太坊，然后进入区块链行业。</p>\n');
INSERT INTO `coin_dev_member` VALUES (784, 'uniswap', 'Moody Salem', 'Uniswap 软件开发工程师', 'https://s2.gongft.com/images/baike/632BE3994EB54E2907332C9F0427003E.png?v=1605518305', 'https://twitter.com/moodysalem91', '', 0, '<p>Moody Salem 是 Uniswap 软件开发工程师。此前，他在 Google、Amazon 等从事过开发工作。</p>\n');
INSERT INTO `coin_dev_member` VALUES (785, 'ethereum-classic', 'Igor Artamonov', '创始人兼首席技术官', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (786, 'litecoin', '李启威', '莱特币创始人', 'https://s2.gongft.com/images/baike/9916c1a2ebb2652997844f088e66eca1.jpg', 'https://twitter.com/SatoshiLite', 'https://www.linkedin.com/in/chocobo/', 0, '<p>Charlie lee（李启威）是一名亚裔美国人，1999年毕业于麻省理工大学，拥有学士和硕士学位，攻读专业为电气工程和计算机科学。Charles Lee（李启威） 是莱特币的创始人，他曾是Coinbase公司的工程总监，也是大型数字货币交易平台比特币中国CEO 李启元的弟弟。</p>\n');
INSERT INTO `coin_dev_member` VALUES (787, 'litecoin', 'Xinxi Wang', 'LTCFoundation,创始成员和董事', 'https://s2.gongft.com/image/20190622/6311561169604756.png', 'https://twitter.com/TheRealXinxi', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (788, 'litecoin', 'Franklyn Richards ', 'LTCFoundation,创始成员董事| |首席设计师', 'https://s2.gongft.com/image/20190622/9881561169788678.png', 'https://twitter.com/FranklynCrypto', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (789, 'cosmos', 'Ethan Buchman', 'Tendermint 联合创始人兼首席技术官。', 'https://s2.gongft.com/images/baike/28e1de0e4974c92f37614f66a1305420.jpg', 'https://twitter.com/buchmanster', 'https://www.linkedin.com/in/ethan-buchman-10b34944/', 0, '\n                            <p>Ethan Buchman 是 Tendermint 首席技术官，已经在 Eris Industries 领导区块链开发近两年时间，也是互联网上的生物物理学家。 他拥有细胞生物学、神经科学、数学、机器学习、分布式计算的背景，目标是建立工具帮助人类自我组织优化系统，好像生命体内的分子结构一样。</p>\n<p>他也是加拿大安大略省加密咨询机构 CoinCulture 首席执行官，经营着比特币 ATM，并促进加密货币的广泛采用。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (790, 'cosmos', 'Jack Zampolin', 'Cosmos 与 Tendermint 核心开发者。', 'https://s2.gongft.com/images/baike/40c5e5ecff9d9ca27ed7934322ad89bc.jpg', 'https://twitter.com/Jack_Zampolin/', 'https://www.linkedin.com/in/jackzampolin', 0, '\n                            <p>Jack Zampolin 是 Cosmos 与 Tendermint 核心开发者，从事区块链与去中心化应用的开发工程师，此前为 Blockstack 贡献代码。</p>\n<p>他擅长的开发语言包括 Go、Javascript、Shell，部署平台经验包括 GCE、AWS、Azure、DO、Docker、Kubernetes、Ansible、Terraform 等。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (791, 'cosmos', 'Zaki Manian', 'Tendermint  实验室负责人。', 'https://s2.gongft.com/images/baike/62ec46c7e9f09cbd9af264175586ac72.jpg', 'https://twitter.com/zmanian', 'https://www.linkedin.com/in/zmanian', 0, '\n                            <p>Zusted Manian 是区块链和加密货币技术发展的多产者，在密码学和分布式共识系统方面拥有深厚的专业知识。他是 Trusted IoT Alliance 执行董事，他是 Tendermint 实验室负责人，还是 Cosmos 项目的顾问，还是 Amino Capitol 的顾问……</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (792, 'chainlink', 'Sergey Nazarov', 'CEO', 'https://s2.gongft.com/image/20190620/1831560993895528.png', '', 'https://www.linkedin.com/in/sergeydnazarov', 0, '<p>Sergey Nazarov在2011年就已经投身于区块链领域，曾进入First Mark Capital的投资团队。</p>\n');
INSERT INTO `coin_dev_member` VALUES (793, 'chainlink', 'Steve Ellis', 'CTO', 'https://s2.gongft.com/image/20190620/3701560994284187.png', '', 'https://www.linkedin.com/in/steveellis0606/', 0, '<p>Steve Ellis曾担任Pivotal Labs的软件工程师和团队负责人，负责保护敏感的HIPAA兼容数据并构建可扩展的支付自动化软件。</p>\n');
INSERT INTO `coin_dev_member` VALUES (794, 'crypto-com-chain', 'Kris Marszalek', '联合创始人&CEO', 'https://s2.gongft.com/images/baike/8f2588e1d11067cb8c65139328c12abf.jpg', 'https://twitter.com/Kris_HK', 'https://www.linkedin.com/in/krismarszalek/', 0, '<p>总部位于香港的经验丰富的公司建造商，收入在0到1亿美元之间翻了两倍，有两个出口。Ensogo首席执行官，BEECRAZY创始人(2013年以2100万美元的价格卖给iBuy Group)。</p>\n\n<p>Kris Marszalek是Monaco联合创始人兼首席执行官，做开创性的加密货币支付平台。Monaco在 2017年募集约2670万美元，现在已经更名为Crypto.com，旨在建立首个全球区块链金融机构与消费品牌。他积极参与加密社区的活动，尤其在亚洲，为区块链发展做出贡献。</p>\n');
INSERT INTO `coin_dev_member` VALUES (795, 'crypto-com-chain', 'Rafael Melo', '联合创始人兼首席财务官', 'https://s2.gongft.com/image/20190619/8031560935866722.png', '', 'https://www.linkedin.com/in/rmmbacpa/', 0, '<p>15年金融从业经验，对亚洲风险、合规和移动支付生态系统有深入了解。曾担任在澳大利亚证交所上市的Ensogo的首席财务官，获得唯品会(VIPSHOP)的战略投资，并从富达(Fidelity)、高盛(Goldman Sachs)和贝莱德(BlackRock)等蓝筹机构融资逾5000万澳元。</p>\n');
INSERT INTO `coin_dev_member` VALUES (796, 'crypto-com-chain', 'Gary Or', '联合创始人兼首席技术官', 'https://s2.gongft.com/image/20190619/4191560935618379.png', '', 'https://www.linkedin.com/in/pinglamb/', 0, '<p>黑客，产品设计师，企业家，9年全堆栈工程经验(RoR, Elixir, Golang)，对机器学习和人工智能有浓厚兴趣。</p>\n');
INSERT INTO `coin_dev_member` VALUES (797, 'crypto-com-chain', 'Bobby Bao', '联合创始人兼公司发展主管', 'https://s2.gongft.com/image/20190619/9461560936005834.png', 'https://twitter.com/bobbybaocrypto', 'https://www.linkedin.com/in/bobby-bao/', 0, '<p>在投资银行、企业发展、投资者关系方面有丰富的经验。Ensogo corp .)开发主管,投资银行家在中国复兴(华兴)、德勤、美林(Merrill Lynch)。在华兴创业期间，他参与了一些里程碑式的交易，包括滴滴和快的合并(现在的滴滴出行)，以及京东(纳斯达克:京东)的战略企业发展项目。</p>\n');
INSERT INTO `coin_dev_member` VALUES (798, 'crypto-com-chain', 'Eric Anziani', '首席运营官', 'https://s2.gongft.com/images/baike/C8F9A5F8E90323672C50426A3A1077D5.png?v=1592548987', 'https://twitter.com/ericnode', 'https://www.linkedin.com/in/ericanziani/', 0, '<p>在金融服务、零售和技术领域拥有12年的战略、伙伴关系和创新经验。曾在伦敦、巴黎、新加坡和东京的高盛、麦肯锡和贝宝任职。最近，Eric领导了Global Fashion Group的战略团队，带领超过9000名员工在24个市场开展了重大的跨地区战略项目。</p>\n');
INSERT INTO `coin_dev_member` VALUES (799, 'monero', 'Riccardo Spagni', 'Monero 核心开发，项目负责人', 'https://s2.gongft.com/images/baike/fe605be47d32b8969212067fc1ddc898.jpg', 'https://twitter.com/fluffypony', '', 0, '<p>Riccardo Spagni 是 Monero 核心团队成员，也是 Monero 项目目前的管理者、主要维护者。他具有信息学与物流的背景，早于 2011 年初开始参与比特币开发，2012 年参与到各种加密货币相关的项目开发中，并在 2017 年推出了 Globee 多币种支付处理器。</p>\n');
INSERT INTO `coin_dev_member` VALUES (800, 'stellar', 'Jed McCaleb', '恒星基金会的联合创始人。', 'https://s2.gongft.com/images/baike/200502807f7d0d0d4e7eead9862a5cb1.jpg', 'https://twitter.com/jedmccaleb', 'https://www.linkedin.com/in/jed-mccaleb-4052a4', 0, '\n                            <p>Jed McCaleb 对比特币有着浓厚的兴趣，他几乎参与并见证了比特币发展史上的许多重大事件，无论是参与创立 Mt.Gox，或者是建立 Ripple，并在之后离开再创建 Stellar，其中都有无数精彩的故事和八卦。</p>\n<p>另外，他也是全球最早的 P2P 共享软件 eDonkey 电驴的创办者，在电驴的协议中，定义了一系列传输、压缩和打包的标准，甚至还定义了一套积分的标准，你上传的数据量越大，积分越高，下载的速度也越快。比特币似乎也很好的继承了这一优点。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (801, 'stellar', 'Joyce Kim', 'SparkChain Capital 联合创始人兼管理合伙人。', 'https://s2.gongft.com/images/baike/5355a87fa6fdb64a844d5f7c3796f892.jpg', 'https://twitter.com/joyce', 'https://www.linkedin.com/in/joycekim', 0, '\n                            <p>Joyce Kim 是 SparkChain Capital 联合创始人兼管理合伙人，LiteracyBridge 董事会成员，并参与创办 Stellar。</p>\n<p>作为加密货币领域的专家，她为银行、政府组织、联合国等提供了加密与区块链咨询，并为众多与加密相关的项目和 ICO 提供建议。</p>\n<p>她还担任麻省理工学院媒体实验室的主任研究员。她在加入 Stellar 之前，曾在 Freestyle Capital 做风险投资。她于 19 岁毕业于康奈尔大学，随后在哈佛大学、哥伦比亚大学法学院读研究生。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (802, 'stellar', 'Nicolas Barry', 'CTO', 'https://s2.gongft.com/image/20190622/9681561186316937.png', '', '', 0, '<p>Nicolas在法国图卢兹的ENSEEIHT大学获得计算机科学和数学硕士学位。<br />\nNicolas擅长将潜在的技术转化为最实用且最受益的东西。他喜欢努力修补软件和解决分布式问题。他之前帮助微软和Salesforce建立了大规模的系统。</p>\n');
INSERT INTO `coin_dev_member` VALUES (803, 'stellar', 'David Mazières', '首席科学家', 'https://s2.gongft.com/image/20190622/5521561185953893.png', 'https://twitter.com/dmazieres', 'https://www.linkedin.com/in/david-mazi%C3%A8res-20a92924/', 0, '<p>DavidMazi&egrave;res是斯坦福大学计算机科学教授，领导安全计算机系统集团。Mazi&egrave;res教授获得哈佛大学计算机科学学士学位和博士学位。麻省理工学院电气工程与计算机科学专业。他的研究兴趣包括操作系统和分布式系统，重点是安全性。</p>\n');
INSERT INTO `coin_dev_member` VALUES (804, 'flow', 'Roham Gharegozlou', 'CEO', 'https://s2.gongft.com/images/baike/E6CFA3C5A3DA1045675A0673AD1655EE.png?v=1600914558', '', '', 0, '<p>Roham是Dapper Labs的首席执行官，Dapper Labs是CryptoKitties，Flow和NBA Top Shot的创造者。他拥有斯坦福大学的经济学学士学位和生物科学双学士学位和硕士学位。在Dapper Labs之前，Roham是Axiom Zen的创始人兼首席执行官。</p>\n');
INSERT INTO `coin_dev_member` VALUES (805, 'flow', 'Dieter “dete” Shirley', '创始人兼首席技术官', 'https://s2.gongft.com/images/baike/365E40F00A3A699E1CB273C7F558311B.png?v=1600914843', '', '', 0, '<p>迪特（Dieter）在塑造新兴技术的第一波浪潮中发展了专长。他最近与他人共同创立了CryptoKitties，并撰写了ERC-721提案，该提案在以太坊上定义了不可替代的代币。在加入CryptoKitties之前，Dieter是Axiom Zen的首席架构师。</p>\n');
INSERT INTO `coin_dev_member` VALUES (806, 'flow', 'Mikhael Naayem', '首席商务官', 'https://s2.gongft.com/images/baike/7283AE6622E5A0DADF8FCB601B5C8D40.png?v=1600914913', '', '', 0, '<p>在帮助创办Dapper Labs之前，Mik自公司成立以来一直担任Axiom Zen的董事会成员。在CryptoKitties推出前一个月，他全职加入Axiom Zen。在加入Axiom Zen之前，Mik是Fuel的创始人兼首席执行官，该平台在他成长为拥有2.25亿用户之后，于2017年被出售给Animoca。</p>\n');
INSERT INTO `coin_dev_member` VALUES (807, 'flow', 'Alex Shih', '首席财务官', 'https://s2.gongft.com/images/baike/75B418943ECF82EACB67C4A69215F241.png?v=1600914999', '', '', 0, '<p>Alex是Axiom Zen和Dapper Labs的首席财务官，领导战略财务部门。他还担任过Dapper Labs和ZenHub董事会的董事。Alex拥有斯坦福大学管理科学与工程学士学位和硕士学位。</p>\n');
INSERT INTO `coin_dev_member` VALUES (808, 'vechaincom', '陆扬', 'CEO', 'https://s2.gongft.com/image/20190624/1401561362031779.png', '', 'https://www.linkedin.com/in/sunny-lu-55456915/', 0, '<p>陆扬先生毕业于上海交通大学，电子与通信工程专业。拥有超过15年的500强跨国企业&nbsp;IT&nbsp;高管经验，曾任路易威登大中华区首席信息官。他在计算机、网络通信等领域拥有坚实的技术背景，并在信息系统技术战略及管理，企业数字化革命及数字化创新领域积累了丰富的经验。陆扬先生于2015年正式启动唯链（VeChain）项目。</p>\n');
INSERT INTO `coin_dev_member` VALUES (809, 'vechaincom', '张杰', 'CFO', 'https://s2.gongft.com/image/20190624/5711561362326333.png', '', 'https://www.linkedin.com/in/jie-zhang-9426a74a/', 0, '<p>张杰先生拥有超过14年四大会计事务所工作经验，曾任普华永道中国和德勤英国高级经理。2015&nbsp;年加入唯链（VeChain）管理团队，致力于数字资产管理框架的研究与制定，区块链治理架构建立与实施。</p>\n');
INSERT INTO `coin_dev_member` VALUES (810, 'vechaincom', '顾建良', 'CTO', '', '', 'https://www.linkedin.com/in/jianliang-gu-260506157/', 0, '<p>顾建良先生毕业于上海大学控制理论与控制工程硕士学位。曾就职于TCL通讯担任技术总监，在嵌入式软硬件开发及管理具有超过16年的经验。2017年加入唯链（VeChain）负责技术开发与管理，致力于推动物联网与区块链技术的结合与发展。</p>\n');
INSERT INTO `coin_dev_member` VALUES (811, 'eos', 'Brendan Blumer', 'EOS 幕后 Block.one 创始人。', 'https://s2.gongft.com/images/baike/bee3ebe369caee6cc78722b1bb1a1b71.jpg', 'https://twitter.com/BrendanBlumer', 'https://www.linkedin.com/in/brendanblumer/', 0, '\n                            <p>Brendan Blumer 生于 1986 年 8 月 8 日，常年在亚洲活动的美国科技企业家。他在 15 岁开始创业，第一家企业 GaMeCLiFF 被 Internet Gaming Entertainment 即现在的 IMI Exchange 收购。他在 IGE 将账户销售部门的业务增长到每年 500 万美元的高利润。此后，他创办 Accounts.net，成为全球最大的游戏账户销售网站，在三个月内，公司的月收入超过 100 万美元。2010 年，他在香港创立 Okay.com，负责建立房地产企业软件，供公司直接聘用的房地产经纪人使用，内部软件平台结合了专有的 CRM 和物业数据库，为亚洲的房地产经纪人提供完全移动的虚拟办公室，已成为香港最大的数字地产代理商。</p>\n<p>当然，Brendan Blumer 也是区块链的早期投资者，于 2016 年转为全职参与，与 Dan Larimer 共同创立 Block.one。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (812, 'eos', 'Dan Larimer', '首席技术官', 'https://s2.gongft.com/image/20190621/8331561109672471.png', 'https://twitter.com/danlarimer', 'https://www.linkedin.com/in/daniel-larimer-0a367089', 0, '<p>Dan&nbsp;Larimer，即Bytemaster，简称BM，现任Block.one首席技术官，是EOS创始人，也是BTS和Steemit的创始人，是一个崇尚自由市场的程序大神。同为天才的技术人员，BM经常被拿来和V神相比。BM打造的EOS则被称为最有可能取代以太坊地位的区块链操作系统。&nbsp;</p>\n');
INSERT INTO `coin_dev_member` VALUES (813, 'dfinity', 'Dominic Williams', '创始人兼首席科学家', 'https://s2.gongft.com/images/baike/6D9A2650030618930A2F6B26E7B96D09.png?v=1591672174', 'http://twitter.com/dominic_w', 'https://www.linkedin.com/in/thedwilliams', 0, '<p>Dominic是一位加密理论家和企业家。他最近的研究包括阈值中继和PSC链，验证塔和树以及USCID，并提出了新的想法，例如&ldquo; Sybil Resistance的3 E&rdquo;。此前，他使用自己的分布式系统（托管了数百万用户）来运行由风投支持的MMO游戏。</p>\n');
INSERT INTO `coin_dev_member` VALUES (814, 'dfinity', 'Artia Moghbel', '首席运营官', 'https://s2.gongft.com/images/baike/CF7B1B290B5B0F93A657865B3A1C9216.png?v=1591672501', 'https://twitter.com/artia', 'https://www.linkedin.com/in/artiam', 0, '<p>Artia作为初创企业家，区块链爱好者和风险投资家（也曾投资过Dominic的前一家公司），为DFINITY带来了丰富的运营经验。他加入该团队的目的是扩大其内部运营和非技术团队。此前，他获得了哥伦比亚大学的理学学士学位。</p>\n');
INSERT INTO `coin_dev_member` VALUES (815, 'decentraland', 'Ari Meilich', '项目负责人', 'https://s2.gongft.com/image/20190622/5401561169442026.png', 'https://twitter.com/arimeilich', 'https://www.linkedin.com/in/arimeilich/', 0, '');
INSERT INTO `coin_dev_member` VALUES (816, 'tezos', 'Arthur Breitman', 'Tezos 联合创始人兼首席技术官。', 'https://s2.gongft.com/images/baike/b6109ab905bcef4049a0ea3c382a9235.jpg', 'https://twitter.com/arthurb', '', 0, '\n                            <p>Arthur Breitman 是 Tezos 联合创始人兼首席技术官，曾在高盛、摩根士丹利担任定量分析师。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (817, 'tezos', 'Kathleen Breitman', 'Tezos 联合创始人兼首席执行官。', 'https://s2.gongft.com/images/baike/fd458c71458b69ed136c957d97fb3cb7.jpg', 'https://twitter.com/breitwoman', 'https://www.linkedin.com/in/breitwoman/', 0, '\n                            <p>Kathleen Breitman 是 Dynamic Ledger Solutions 首席执行官，亦是 Tezos 区块链的开发商。此前，她在由近百家金融公司组成的区块链联盟 R3 担任高级战略助理，还曾在埃森哲、Bridgewater 协会、《华尔街日报》工作。她毕业于康奈尔大学。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (818, 'chiliz', 'Emma Diskin', '首席运营官', 'https://s2.gongft.com/images/baike/60BF460A716B04C7F14E709EE9DB0147.png?v=1591684689', '', 'https://www.linkedin.com/in/emmalucasdiskin/', 0, '');
INSERT INTO `coin_dev_member` VALUES (819, 'chiliz', 'Max Rabinovitch', '首席战略官', 'https://s2.gongft.com/images/baike/2C355E36A597A9F58CA7BDC78B9D0A28.png?v=1591684815', '', 'https://www.linkedin.com/in/max-rabinovitch/', 0, '');
INSERT INTO `coin_dev_member` VALUES (820, 'aave-new', 'Jordan Lazaro Gustave', '首席运营官', 'https://s2.gongft.com/image/20190628/6031561704396604.png', '', 'https://www.linkedin.com/in/jordan-lazaro-gustave-32018976/', 0, '<p>Jordan以其在创业、国际关系和创新管理方面的技能，为民主的社区作出了贡献。</p>\n');
INSERT INTO `coin_dev_member` VALUES (821, 'aave-new', 'Stani Kulechov', '创始人，CEO', 'https://s2.gongft.com/image/20190628/5371561704206002.png', '', 'https://www.linkedin.com/in/stanislav-kulechov-361284132/', 0, '<p>Stani是区块链社区成员，具有创建金融智能合同的法律背景。</p>\n');
INSERT INTO `coin_dev_member` VALUES (822, 'aave-new', 'Nolvia Serrano', '首席营销官', 'https://s2.gongft.com/image/20190628/3641561704635040.png', '', 'https://www.linkedin.com/in/nolvia-serrano-ba7362b2/', 0, '<p>Nolvia对加密货币和区块链技术有着强烈的热情。她也是拉丁美洲密码社区的活跃成员，并在投资公司的营销部门工作。</p>\n');
INSERT INTO `coin_dev_member` VALUES (823, 'thetatoken', 'Mitch Liu', '联合创始人/首席执行官', 'https://s2.gongft.com/images/baike/35C75D2E080B61825ABFE947ADF7A056.png?v=1592897005', '', '', 0, '<p>THETA.tv联合创始人；Gameview Studios联合创始人；Tapjoy联合创始人；麻省理工学院计算机科学与工程学士；斯坦福大学商学院管理学硕士。</p>\n');
INSERT INTO `coin_dev_member` VALUES (824, 'thetatoken', 'Jieyi Long', '联合创始人/首席技术官', 'https://s2.gongft.com/images/baike/584067F93F70DC6F9E02EDFA652C3D3B.png?v=1592897351', '', '', 0, '<p>THETA.tv联合创始人；北京大学微电子科学与工程学士；美国西北大学计算机工程博士；曾研发多项专利技术，包括VR实时流媒体和视频游戏即时回放技术。</p>\n');
INSERT INTO `coin_dev_member` VALUES (825, 'thetatoken', 'Ryan Nichols', '首席产品官', 'https://s2.gongft.com/images/baike/8A89765ECF24660C0B8ED29C29BBC559.png?v=1592897562', '', '', 0, '<p>THETA.tv首席产品官；曾为多个平台设计和推出虚拟货币系统。腾讯微信项目总监；一款实时美食直播应用的联合创始人。</p>\n');
INSERT INTO `coin_dev_member` VALUES (826, 'axieinfinity', 'Trung Thanh Nguyen', 'CEO', 'https://s2.gongft.com/images/baike/F95C1120C04930F0B64EF94B0FB09B3E.png?v=1605081083', '', '', 0, '<p>Trung参与了从产品到市场营销的所有关键决策，并领导Axie Infinity在越南的业务。19岁时，Trung与他人共同创立了Lozi，并担任CTO。</p>\n\n<p>vn是一家早期的越南电子商务初创公司，已筹集了约1000万美元的资金，目前仍在运营。当Lozi成为一家稳定的公司，他就离开了这家公司。在创立Axie Infinity之前，Trung还在trust Social(最近由Sequoia牵头的2500万轮融资)和Anduin Transactions做过一些工作。</p>\n\n<p>Trung代表越南参加了在俄罗斯叶卡捷琳堡举行的2014年ACM-ICPC世界总决赛。</p>\n');
INSERT INTO `coin_dev_member` VALUES (827, 'axieinfinity', 'Andy Ho', 'CTO', 'https://s2.gongft.com/images/baike/93B623D9A8200E5F29D6C517EF31F47E.png?v=1605081256', '', '', 0, '<p>Andy曾在安杜因交易公司(Anduin Transactions)担任软件工程师，并在谷歌和Paypal实习。</p>\n\n<p>安迪毕业于新加坡南洋理工大学，并代表新加坡参加了在摩洛哥马拉喀什举行的2015年ACM-ICPC世界总决赛。</p>\n');
INSERT INTO `coin_dev_member` VALUES (828, 'axieinfinity', 'Aleksander Leonard Larsen', 'COO', 'https://s2.gongft.com/images/baike/D6F1CFB44AAB12E101F555B41ECBA36B.png?v=1605081329', '', '', 0, '<p>Aleksander负责Axie Infinity的所有商务业务。他还在区块链游戏联盟担任委员会成员，并担任秘书职务。在Axie Infinity之前，他在挪威担任经理，业余时间从事游戏内容创造和竞技游戏。在《魔兽争霸2》中，他是欧洲排名前200的选手之一，并在《魔兽争霸3》和《魔兽争霸2》中代表挪威国家队参赛。</p>\n');
INSERT INTO `coin_dev_member` VALUES (829, 'true-usd', 'Danny An', '联合创始人/CEO', 'https://s2.gongft.com/image/20190620/4231560994969332.png', '', 'https://www.linkedin.com/in/djan92', 0, '');
INSERT INTO `coin_dev_member` VALUES (830, 'true-usd', 'Rafael Cosman', '联合创始人/CTO', 'https://s2.gongft.com/image/20190620/2541560995058635.png', '', 'https://www.linkedin.com/in/rafaelcosman', 0, '');
INSERT INTO `coin_dev_member` VALUES (831, 'true-usd', 'Stephen Kade', '联合创始人/COO', 'https://s2.gongft.com/image/20190620/2131560995177679.png', '', 'https://www.linkedin.com/in/stephenkade/', 0, '');
INSERT INTO `coin_dev_member` VALUES (832, 'true-usd', 'Tory Reiss', '联合创始人，合伙企业和业务发展主管', 'https://s2.gongft.com/image/20190620/7751560995315627.png', '', 'https://www.linkedin.com/in/toryreiss', 0, '');
INSERT INTO `coin_dev_member` VALUES (833, 'bitcoin-cash-sv', 'Steve Shadders', '技术总监', '', '', '', 0, '<p>负责项目监管事宜，并与赞助商和业内人士进行联络。史蒂夫于2011年开始投身比特币事业，为比特币的发展贡献力量。他是早期首批开源矿池引擎的开发设计者，也曾是BitcoinJ创始团队成员。</p>\n');
INSERT INTO `coin_dev_member` VALUES (834, 'bitcoin-cash-sv', 'Daniel Connolly', '首席开发员', '', '', '', 0, '<p>在加入nChain前曾在企业系统工作了20年，并在多个联合国机构担任过高级信息技术（IT）专家。多年来，丹尼尔一直默默为比特币的发展贡献力量，为Electron Cash项目提供技术支持，也是BitcoinJ-Cash项目的主要开发者之一。</p>\n');
INSERT INTO `coin_dev_member` VALUES (835, 'zcash', 'Zooko Wilcox', 'Zcash 创始人兼首席执行官。', 'https://s2.gongft.com/images/baike/214475adbb11a9cd28cb962ba8215d49.jpg', 'https://twitter.com/zooko', 'https://www.linkedin.com/in/zookow/', 0, '\n                            <p>Zooko Wilcox 是 Zcash 创始人兼首席执行官，从前是 Least Authority 首席执行官，负责开发、安全、运营和客户支持等领域。他在安全分布式系统，开源软件及初创公司方面拥有 20 多年的丰富经验，以 DigiCash、Mojo Nation、ZRTP、Zooko\'s Triangle 等项目作品而闻名。另外，他也是 Tahoe-LAFS 项目的联合创始人之一。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (836, 'zcash', 'Nathan Wilcox', 'CTO', 'https://s2.gongft.com/image/20190624/0991561360315744.png', 'https://twitter.com/least_nathan', '', 0, '<p>Nathan致力于开放，安全的技术，在软件开发，性能分析和安全审计方面拥有超过10年的经验。在加入Zcash以前，他负责Least Authroity的开发工作，他领导了对以太坊、SpiderOak、Cryptocat、GlobalLeaks和其它项目的安全审计工作。出于乐趣，他喜欢为Python、Rust和以太坊开发应用工具。</p>\n');
INSERT INTO `coin_dev_member` VALUES (837, 'zcash', 'Jack Gavigan', 'COO', 'https://s2.gongft.com/image/20190624/4441561360447849.png', 'https://twitter.com/JackGavigan', '', 0, '<p>Jack在金融技术，网络安全和交易系统方面拥有丰富的经验，曾在德意志银行，瑞士信贷银行和摩根士丹利（也担任过交易员）工作。&nbsp; &nbsp; Jack做过英国政府数字货币和区块链技术方面的顾问。</p>\n');
INSERT INTO `coin_dev_member` VALUES (838, 'zcash', 'Ian Miers', 'Zcash 联合创始人。', 'https://s2.gongft.com/images/baike/70bafe850bed50dcb8c7cfc0428d46ca.jpg', 'https://twitter.com/secparam', 'https://www.linkedin.com/in/ian-miers-27240827/', 0, '\n                            <p>Ian Miers 是康奈尔大学博士后，致力于匿名系统的密码学专家。他是 ZCash 联合创始人，以及 ZeroCash 论文的作者。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (839, 'zcash', 'Andrew Miller', 'IC3 副主任、Zcash 基金会的董事成员。', 'https://s2.gongft.com/images/baike/c897371b272286dfd23634defe3b7a5a.jpg', 'https://twitter.com/socrates1024', '', 0, '\n                            <p>Andrew Miller 是伊利诺伊大学 Urbana-Champaign 分校计算机科学专业相关的助理教授，也是加密货币与智能合约倡议组织 IC3 副主任、Zcash 基金会的董事成员。</p>\n<p>另外，他在马里兰大学网络安全中心得到了博士学位。其研究兴趣主要集中在计算机安全上，结合编程，专注于安全分布式系统和加密货币的设计。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (840, 'zcash', 'Zirui Zhang', 'Zcash 亚太社区的业务拓展。', 'https://s2.gongft.com/images/baike/ad96dce95f5cc146be1e217b173ba97a.jpg', 'https://twitter.com/zirui_z', '', 0, '\n                            <p>Zirui Zhang 是早期的比特币矿工和投资者，游走在亚洲、美国之间，密码世界的极端主义者。她非常关注隐私和互联网安全，并在数字货币领域工作了五年多时间，与亚洲加密货币社区有着千丝万缕的联系。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (841, 'kcs', 'Michael Gan', 'KuCoin 首席执行官。', 'https://s2.gongft.com/images/baike/6778ab5c564ae3371bdb5e3708864ef8.jpg', '', '', 0, '\n                            <p>Michael Gan，现任 KuCoin 首席执行官，此前，他是阿里巴巴集团蚂蚁金服的前技术专家，金融解决方案的资深人士，以及 MikeCRM、KF5.COM 等互联网巨头的高级合伙人。</p>\n<p>他早在 1998 年，即是网易免费个人网站托管服务的首批用户，具备很强的学习能力、敏捷开发经验，热衷于开发团队内部高效和小规模的协作。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (842, 'kcs', 'Eric Don', 'COO', 'https://s2.gongft.com/image/20190620/7951561015945585.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (843, 'kcs', 'Top Lan', 'CTO', 'https://s2.gongft.com/image/20190620/5331561016047181.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (844, 'iota', 'Dominik Schiener', 'IOTA 联合创始人。', 'https://s2.gongft.com/images/baike/6a88bd859a19dad5d0151f20053cfc50.jpg', 'https://twitter.com/DomSchiener', 'https://www.linkedin.com/in/schiener/', 0, '\n                            <p>Dominik Schiener 是 IOTA 联合创始人，为人务实、直接。他目前正忙于开展几个区块链与智能合约的项目，以创建具有社会影响力的去中心化应用。他尤其对于新的治理解决方案特别感兴趣，以创建更高效、便宜和透明的系统。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (845, 'iota', 'Serguei Popov', '科学顾问，也是IOTA 联合创始人。', 'https://s2.gongft.com/images/baike/a74176c7f24899993e4962e9a6ce8a3e.jpg', '', 'https://www.linkedin.com/in/serguei-popov-631bb762/', 0, '<p>Serguei Popov 是 IOTA 联合创始人，拥有莫斯科国立大学的数学博士学位，与 Sergey Ivancheglo、DavidS&oslash;nsteb&oslash;、Dominik Schiener 共同创立 IOTA，具体负责理论和概念方面的工作。</p>\n');
INSERT INTO `coin_dev_member` VALUES (846, 'iota', 'David Sønstebø', '董事会联合主席兼创始人', 'https://s2.gongft.com/image/20190622/8181561194438549.png', 'https://twitter.com/DavidSonstebo', 'https://www.linkedin.com/in/david-s%C3%B8nsteb%C3%B8-760319a5', 0, '<p>我是一个连续创业者，对任何能够推动人类进步的技术都充满激情。我积极参与物联网、分布式账本/区块链/tangle技术、智能城市、数字身份、电子治理和创新硬件设计。</p>\n');
INSERT INTO `coin_dev_member` VALUES (847, 'iota', 'Ralf Rottmann', '董事会成员', 'https://s2.gongft.com/image/20190622/2491561194768328.png', 'https://twitter.com/ralf', 'https://de.linkedin.com/in/rottmann/de', 0, '<p>拉尔夫是一位连续创业者，他将自己的最后一家公司卖给了阿尔卡特朗讯，并且是德国领先的物联网SI产品的grandcentrix的联合创始人。</p>\n');
INSERT INTO `coin_dev_member` VALUES (848, 'iota', 'Lewis Freiberg', '生态系统负责人，高级软件工程师', '', 'https://twitter.com/lewisfreiberg?lang=en', 'https://www.linkedin.com/in/lewisfreiberg/', 0, '');
INSERT INTO `coin_dev_member` VALUES (849, 'maker', 'Rune Christensen', '联合创始人兼首席执行官', 'https://s2.gongft.com/images/baike/4996256b09df187c28d75021f1e5aea5.jpg', 'https://twitter.com/runekek', 'https://www.linkedin.com/in/rune-christensen-5b5220ab/', 0, '<p>Rune Christensen是MakerDAO联合创始人兼首席执行官。由MakerDAO发布的 DAI，是世界上首个在以太坊区块链上使用的稳定币，旨在透过应对市场变化的智能合约系统去除价格波动。他自2015年以来，一直致力于建立分布式自治组织的愿景，以及稳定数字货币的经济基础。此前，他曾参与创办Try China国际招聘公司。</p>\n');
INSERT INTO `coin_dev_member` VALUES (850, 'maker', 'Andy Milenius', '首席技术官', 'https://s2.gongft.com/images/baike/fa22646b47953682b7e0839bbf1494a3.jpg', 'https://twitter.com/RealZandy', 'https://www.linkedin.com/in/andy-milenius-919922123/', 0, '<p>Andy Milenius是MakerDAO首席技术官，对于分布是自治组织及分散治理和引导在线社区的机制设计特别感兴趣。此前，他在Amazon Web Services工作，拥有密歇根大学的计算机科学学位，出生在美国底特律。</p>\n');
INSERT INTO `coin_dev_member` VALUES (851, 'maker', 'Matt Richards', '董事长', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (852, 'maker', '潘超', 'MakerDAO 经济研究员兼中国社区负责人。', 'https://s2.gongft.com/images/baike/14d94aea1b9e00932694f2569f9c644b.jpg', 'https://twitter.com/TheChaology', 'https://www.linkedin.com/in/chao-pan-30294b86/', 0, '\n                            <p>潘超是 MakerDAO 经济研究员、分析师，并负责中国区业务。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (853, 'maker', 'Gregory Di Prisco', 'Distributed Capital 合伙人，在 Maker 负责商务拓展。', 'https://s2.gongft.com/images/baike/e2ee815eb83b46bbe53136c75d56da8e.jpg', '', 'https://www.linkedin.com/in/gregory-di-prisco-0672a9125/', 0, '\n                            <p>Greg Di Prisco 是 Distributed Capital 合伙人，在 Maker 负责商务拓展，也是 EtherIndex 的联合创始人兼首席执行官。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (854, 'maker', 'Henry Doe', 'MakerDAO 设计主管。', 'https://s2.gongft.com/images/baike/6401dd1351a4009c70099f0d9fbb9fca.jpg', 'https://twitter.com/hcdoe', 'https://www.linkedin.com/in/henrydoe/', 0, '\n                            <p>Henry Doe 现任 MakerDAO 设计主管，也是 POINT 产品设计工作室的创始人，服务于包括 MakerDAO、Lloyd\'s of London、Deutsche Bank、MoneyTailor、Vanquis Bank 等客户。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (855, 'maker', 'Martin Lundfall', 'Dapphub、MakerDAO、CirclesUBI 形式化验证的研究员。', 'https://s2.gongft.com/images/baike/dbb9d4d53e26d3814a7f25d3fff63f39.jpg', 'https://twitter.com/martinlundfall', '', 0, '\n                            <p>Martin Lundfall 在 Dapphub、MakerDAO、CirclesUBI 做形式化验证的研究员。在加入 Dapphub 以前，他是去中心化能源市场 TransActive Grid 主要开发者，后来发展成为 Grid +。 他的背景是数学、计算机科学、物理等。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (856, 'maker', 'Joseph Quintilian', 'MakerDAO 交易主管，Distributed Capital Partners 合伙人。', 'https://s2.gongft.com/images/baike/80d16d59bda998a259b0b029a6e7efd8.jpg', 'https://twitter.com/joeqtrader', 'https://www.linkedin.com/in/joseph-quintilian-6a1a80b2/', 0, '\n                            <p>Joseph Quintilian 是 MakerDAO 交易主管，Distributed Capital Partners 合伙人，以及 Etherindex 的联合创始人兼首席财务官，创建了以太坊 ETF。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (857, 'maker', 'Coulter Mulligan', 'MakerDAO 市场推广负责人。', 'https://s2.gongft.com/images/baike/49c6081123728796c4ad7b90b1365e9a.jpg', 'https://twitter.com/CoulterM', 'https://www.linkedin.com/in/coultermulligan/', 0, '\n                            <p>Coulter Mulligan 现任 MakerDAO 市场推广负责人，他富有想象力、责任感，且经验丰富。</p>\n<p>此前，他在 GoPro 负责全球的社会化营销，协调国际团队和机构，通过本地化渠道实施全球战略，使 GoPro 保持在社交媒体的最前沿。用数据驱动的洞察力，确定关键主题与目标。再之前，他在 Tesla 负责内容营销，与多个内部部门合作创建、开发、制作视频和照片广告系列。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (858, 'maker', 'Cyrus Younessi', 'MakerDAO 风险管理。', 'https://s2.gongft.com/images/baike/0e1f6ef20560b795055ed9975f75ce44.jpg', 'https://twitter.com/cyounessi1', 'https://www.linkedin.com/in/cyounessi/', 0, '\n                            <p>Cyrus Younessi 于 2019 年 2 月加入 MakerDAO 团队，做风险管理。此前，他曾在 Scalar Capital 任职研究分析与交易总监，在 Cumberland Mining 做投资分析师，在 DRW 做固定收益交易员。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (859, 'maker', 'Mariano Conti', 'MakerDAO 开发工程师。', 'https://s2.gongft.com/images/baike/546c1b373ed92c290a12c40ca1b261b0.jpg', 'https://twitter.com/nanexcool', 'https://www.linkedin.com/in/marianoconti/', 0, '\n                            <p>Mariano Conti 在 MakerDAO 开发工程师，主要负责开发 Dai 稳定币及信用系统，从智能合约到价格波动管理，从基础设施到用户界面。另外，他也参与 DappHub 计划的一部分。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (860, 'ht', '李林', '董事长/创始人/CEO', 'https://s2.gongft.com/image/20190411/7301554965985373.png', '', 'https://www.linkedin.com/in/leon-li-13621bb8/', 0, '李林先生毕业于清华大学自动化系，连续创业者，曾就职于全球最大的数据库厂商Oracle。李林先生极具互联网行业前瞻眼光，2013年创办了火币网，并将火币网打造成为全球领先的区块链资产金融服务商。');
INSERT INTO `coin_dev_member` VALUES (861, 'ht', '杜均', '联合创始人', 'https://s2.gongft.com/images/baike/549694e380affeb9e0ca79986eebac55.png', '', '', 0, '<p>杜均先生是全球最早从事区块链产业投资的专业投资人，也是知名的数字资产投资和管理人。他曾供职于腾讯、康盛创想等知名互联网企业，并联合创建了数字货币交易平台火币网、区块链专业媒体金色财经等公司，具有专业的行业知识、丰富的创业经验和行业资源，擅长市场运营、资本运作及企业孵化，投资的区块链项目已达数十个。</p>\n');
INSERT INTO `coin_dev_member` VALUES (862, 'ht', '程显峰', 'CTO', 'https://s2.gongft.com/image/20190411/2531554965209229.png', '', '', 0, '<p><span style=\"font-size:10.5pt\"><span style=\"layout-grid-mode:char\"><span style=\"font-family:等线\"><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;微软雅黑&quot;,sans-serif\">程显峰先生负责火币集团技术研发中心管理工作，中国国家互联网金融安全技术专家委员会委员，中国计算机学会区块链专业委员会委员。曾任OneAPM公司首席运营官，积木盒子技术VP，是MongoDB和Docker在中国早期的推动者。</span></span></span></span></span></p>\n');
INSERT INTO `coin_dev_member` VALUES (863, 'ht', '朱嘉伟', 'COO', 'https://s2.gongft.com/image/20190411/4961554965078027.png', '', '', 0, '<p><span style=\"font-size:11.0pt;\"><span style=\"font-family:&quot;微软雅黑&quot;,sans-serif;\">朱嘉伟先生负责火币集团运营中心管理工作，曾就职于 Oracle、凯捷咨询。拥有丰富的公司管理、数据分析实践经验及业务运营管理经验。</span></span></p>\n');
INSERT INTO `coin_dev_member` VALUES (864, 'ht', '李书沸', 'CFO', 'https://s2.gongft.com/image/20190411/3851554965301364.png', '', '', 0, '<p><span style=\"font-family: 微软雅黑, sans-serif; font-size: 11pt;\">李书沸先生负责火币集团财务、并购及董事秘书工作。曾任知名数字资产服务集团CFO、交易所业务CEO，以及百富环球（HK.0327）CFO，在企业管理、战略部署及执行、国际业务拓展、金融科技及电子支付的资本市场拥有超过十五年丰富的专业经验。</span></p>\n');
INSERT INTO `coin_dev_member` VALUES (865, 'ht', '吴树鹏', 'CSO', 'https://s2.gongft.com/image/20190411/9781554965534606.png', 'https://twitter.com/olivewang839', 'https://www.linkedin.com/in/olivia-wang-63143229/', 0, '<p style=\"margin-right:5.0cm; margin:0cm 0cm 0.0001pt; text-align:justify\"><span style=\"font-size:10.5pt\"><span style=\"layout-grid-mode:char\"><span style=\"font-family:等线\"><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;微软雅黑&quot;,sans-serif\">吴树鹏先生负责火币集团安全与风控方面的管理工作，曾就职于滴滴出行、国际化咨询公司、绿盟 科技与政府机构。拥有丰富的信息安全、业务安全、风险管理方面的技术研究与管理经验。</span></span></span></span></span></p>\n');
INSERT INTO `coin_dev_member` VALUES (866, 'fantom', 'Michael Kong', 'CIO', 'https://s2.gongft.com/images/baike/01E3F87F55D12BD1DB6A1B25001F1479.png?v=1592642900', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (867, 'fantom', 'Michael Chen', 'CMO', 'https://s2.gongft.com/images/baike/A2D6CA0BF4F8177E199AF100A853E4DB.png?v=1592643070', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (868, 'fantom', 'Quan Nguyen', 'CTO', 'https://s2.gongft.com/images/baike/AD6C005066EAB3497F244408ADAFBC54.png?v=1592643138', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (869, 'neo', '达鸿飞', '创始人', 'https://s2.gongft.com/image/20190624/2251561339952893.png', 'https://twitter.com/dahongfei', 'https://www.linkedin.com/in/dahongfei/', 0, '<p>昵称达叔，80年人，现居上海。2011年接触比特币，中国比特币社区的早期参与者。2013年起全职从事数字货币社区工作，联合创立了&ldquo;比特创业营&rdquo;。多次在北京、香港等地的数字货币峰会担任演讲嘉宾，担任多个区块链创业项目的顾问。2015年起开始主持&ldquo;小蚁&rdquo;项目，用区块链技术让普通公司都可以进行&ldquo;数字IPO&rdquo;，发行股权，交易股权。与此同时，达鸿飞先生还是Onchain分布科技的CEO。</p>\n');
INSERT INTO `coin_dev_member` VALUES (870, 'neo', '张铮文', '创始人，CTO', 'https://s2.gongft.com/image/20190624/2571561340197355.png', '', '', 0, '<p>拥有信息安全的经验，后来接触区块链技术，加入NEO。</p>\n');
INSERT INTO `coin_dev_member` VALUES (871, 'waves', 'Sasha Ivanov', '创始人兼首席执行官', 'https://s2.gongft.com/image/20190620/7781560992202646.png', '', '', 0, '<p>Sasha Ivanov是一位受过训练的物理学家，也是Waves项目背后的梦想家。</p>\n');
INSERT INTO `coin_dev_member` VALUES (872, 'basic-attention-token', 'Brendan Eich', 'Brave 联合创始人兼首席执行官。', 'https://s2.gongft.com/images/baike/4e1f27a4fedc3fe3faac99d13f51fd4b.jpg', 'https://twitter.com/brendaneich', 'https://www.linkedin.com/in/brendaneich/', 0, '<p>Brendan Eich 是 Brave 与 Basic Attention Token 联合创始人兼首席执行官，他也是 Mozilla 与 Firefox 联合创始人。另外，他也是 JavaScript 主要创造者与架构师，在 1995 年 4 月任职网景期间，为网景浏览器开发出了 JavaScript，之后成为网页浏览器领域应用最广泛的脚本语言之一。1998 年，他协助成立 Mozilla.org，曾任 Mozilla 首席技术官，并曾短暂担任首席执行官</p>\n\n<p>2015 年 5 月，他创办Brave软件公司。2016年1月，该公司发布了Brave网页浏览器。2017年5月，Brendan Eich发起Brave去中心化网页浏览器，仅 30 秒即完成约 3500 万美元的初始代币众筹。</p>\n\n<p>&ldquo;从一开始就作为OTOY的顾问，我为他们的交易和安全性新架构表示赞赏。到目前为止，Render Token是我在该领域中看到的最有趣的项目，因为已经有一个由OTOY主导的服务市场，可以通过区块链技术对其进行合理化和收获。&rdquo;</p>\n');
INSERT INTO `coin_dev_member` VALUES (873, 'basic-attention-token', 'Brian Bondy', 'BAT项目联合创始人&浏览器首席工程师', 'https://s2.gongft.com/image/20190624/7991561363134644.png', '', '', 0, '<p>先前从事Khan Academy, Mozilla, Evernote研发&nbsp;&nbsp;</p>\n');
INSERT INTO `coin_dev_member` VALUES (874, 'nexo', 'Kosta Kantchev', '经营合伙人', 'https://s2.gongft.com/images/baike/9F854D05FDBF1C7E36BCED182CBE1952.png?v=1593329677', '', 'https://www.linkedin.com/in/kostakantchev/', 0, '<p>Kosta是Credissimo的创始人之一，有远见，对欧洲科技金融集团的10年来成功做出了不可或缺的贡献。作为比特币的早期采用者，他快速意识到了区块链技术的潜力，并且在Credissimo开发了最早的全球加密货币贷款偿付系统之一。</p>\n');
INSERT INTO `coin_dev_member` VALUES (875, 'nexo', 'Georgi Shulev', '经营合伙人', 'https://s2.gongft.com/images/baike/D29CE61B0A6584C9FE88DA764C8BEC3E.png?v=1593329760', '', 'https://www.linkedin.com/in/georgi-shulev-5701589/', 0, '<p>Georgi有银行业工作背景，在奥地利联合信贷银行、雷曼兄弟和欧洲投资银行积累了大量并购、金融分析方面的经验。通过负责Credissimo的业务开发和国际扩展，他进一步巩固了自己在科技金融方面的经验。</p>\n');
INSERT INTO `coin_dev_member` VALUES (876, 'nexo', 'Antoni Trenchev', '经营合伙人', 'https://s2.gongft.com/images/baike/CE7AB8DE1F22F269279AEE410EAF3D36.png?v=1593329963', '', 'https://www.linkedin.com/in/antoni-trenchev/', 0, '<p>2011年起，Antoni便成了加密货币粉丝。作为国家议会成员和去中心化方案的忠实信徒，他执着地提倡着并最后成功使议会通过与多种电子政府服务有关的区块链解决方案立法，其中最出名的便是电子投票。他参加了电商平台的开发，并担任了Credissimo的首席创意官。</p>\n');
INSERT INTO `coin_dev_member` VALUES (877, 'nexo', 'Vasil Petrov', '首席技术官', 'https://s2.gongft.com/images/baike/C764A74995088428C5187541B122BB41.png?v=1593330042', '', 'https://www.linkedin.com/in/v-v-petrov/', 0, '<p>Vasil是区块链技术的早期自主采用者。他在系统行政、后端开发和高负载和全周期项目方面拥有超过16年的经验。截至目前，他最大的成就是联合创始以及担任美国多个频道和网络服务提供商和互动服务的分销商，为超过15万名用户服务。</p>\n');
INSERT INTO `coin_dev_member` VALUES (878, 'dash', 'RYAN TAYLOR', 'CEO', 'https://s2.gongft.com/image/20190622/5531561191290062.png', '', 'https://www.dash.org/forum/members/ryan-taylor.1654/', 0, '');
INSERT INTO `coin_dev_member` VALUES (879, 'dash', 'BOB CARROLL', 'CTO', 'https://s2.gongft.com/image/20190622/7931561191541023.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (880, 'dash', 'GLENN AUSTIN', 'CFO', 'https://s2.gongft.com/image/20190622/6531561191671127.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (881, 'dash', 'ROBERT WIECKO', 'COO', 'https://s2.gongft.com/image/20190622/6221561191802743.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (882, 'dash', 'FERNANDO GUTIERREZ', '首席营销官', 'https://s2.gongft.com/image/20190622/0581561192159663.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (883, 'dash', 'NATHAN MARLEY', '副首席技术官', 'https://s2.gongft.com/image/20190622/3861561192322028.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (884, 'dash', 'ANDY FREER', '首席架构师', 'https://s2.gongft.com/image/20190622/3131561192456000.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (885, 'blockstack', 'Muneeb Ali', 'Blockstack 联合创始人。', 'https://s2.gongft.com/images/baike/a8c0bf1f499a157c6940efe128e6b0cd.jpg', '', '', 0, '\n                            <p>Muneeb Ali 是 Blockstack 联合创始人，旨在搭建分布式应用的全栈解决方案。他曾在 TEDx 等论坛上发表演讲，传播加密数字货币、区块链，并撰写了大量相关主题的学术刊物与白皮书。另外，他还拥有普林斯顿大学分布式系统的博士学位。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (886, 'blockstack', 'Ryan Shea', 'Blockstack 联合创始人。', 'https://s2.gongft.com/images/baike/6db0a757134595611ea64d13813496d0.jpg', '', '', 0, '\n                            <p>Ryan Shea，Blockstack 联合创始人，也是 Lightning、Embark 等区块链项目种子轮的投资者。此前，他参与创立了名为 GraphMuse 软件即服务的创业公司。他是普林斯顿创业俱乐部的会长，毕业于普林斯顿大学机械和航空航天工程学位，辅修计算机科学。他在密码学和区块链技术方面写过几个流行的开源库，喜欢建立公司、开发产品和发展社区。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (887, 'zilliqa', 'Prateek Saxena', '首席科学顾问', 'https://s2.gongft.com/image/20190620/9991561011758670.png', 'https://twitter.com/prateekatcs', 'https://www.linkedin.com/in/prateek-saxena-8b241347/', 0, '');
INSERT INTO `coin_dev_member` VALUES (888, 'loopring', 'Daniel Wang', '创始人', 'https://s2.gongft.com/image/20190622/1061561193842150.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (889, 'loopring', 'Johnston Chen', 'COO', 'https://s2.gongft.com/image/20190622/0941561193994992.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (890, 'enjin-coin', 'Maxim Blagov', '创始人兼首席执行官', 'https://s2.gongft.com/image/20190620/9291561014396351.png', '', 'https://www.linkedin.com/in/maxim-blagov-24787214/', 0, '');
INSERT INTO `coin_dev_member` VALUES (891, 'enjin-coin', 'Witek Radomski ', '创始人兼首席技术官', 'https://s2.gongft.com/image/20190620/1031561014495231.png', '', 'https://www.linkedin.com/in/witek-radomski-5318a274/', 0, '');
INSERT INTO `coin_dev_member` VALUES (892, 'bitcoin-gold', 'Jack Liao', '联合创始人，理事会成员', 'https://s2.gongft.com/image/20190624/4341561360999195.png', '', 'https://www.linkedin.com/in/bitcoingold/', 0, '');
INSERT INTO `coin_dev_member` VALUES (893, 'bitcoin-gold', 'Robert Kuhne', '联合创始人', 'https://s2.gongft.com/image/20190624/4861561361296396.png', 'https://twitter.com/rbtkhn', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (894, 'bitcoin-gold', 'h4x3rotab', '首席开发者，联合创始人', '', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (895, 'gnosis-gno', 'Stefan George', '联合创始人，首席技术官', 'https://s2.gongft.com/image/20190625/4261561451218408.png', 'https://twitter.com/stefandgeorge', 'https://www.linkedin.com/in/stefangeorge/', 0, '');
INSERT INTO `coin_dev_member` VALUES (896, 'gnosis-gno', 'Matt Liston', '首席策略师', 'https://s2.gongft.com/image/20190625/7151561451570446.png', 'https://twitter.com/malloc8', 'https://www.linkedin.com/in/matt-liston-b041088a/', 0, '');
INSERT INTO `coin_dev_member` VALUES (897, 'nem', 'Lon Wong', 'NEM基金会创始人', 'https://s2.gongft.com/image/20190624/0601561358465811.png', '', '', 0, '<p>Lon Wong,就职于ProximaX ,现任CEO, NEM基金会创始人一职。作为行业享有盛名的大咖，Lon Wong行事低调，对工作热情饱满，多次受邀作为嘉宾出席各类大会，并发表了精彩演讲。<br />\n2018年08月24日,Lon Wong受邀参加了由Boolan.com 博览网在杨浦区国定东路88号合生国际广场内主办的《2018全球区块链技术大会》,并发表了精彩演讲。</p>\n');
INSERT INTO `coin_dev_member` VALUES (898, 'nem', 'Jeff McDonald', '董事会副主席', 'https://s2.gongft.com/image/20190624/8421561358702468.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (899, 'nem', 'Ewan', '创始成员', 'https://s2.gongft.com/image/20190624/8971561358029888.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (900, 'nem', 'Erik Van Himbergen', '创始成员', 'https://s2.gongft.com/image/20190624/0611561358204593.png', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (901, 'decred', 'Alex Yocom-Piatt', 'Decred 创始成员、核心开发者。', 'https://s2.gongft.com/images/baike/d85f9f69b7453e404e67918d9ce2c983.jpg', '', '', 0, '\n                            <p>Alex Yocom-Piatt 是 Decred 创始成员之一，他目前负责 Decred 跨平台钱包 GUI Decrediton 的开发工作，并且还为 Decred 后端钱包软件 dcrwallet 提供支持。</p>\n                            \n                        ');
INSERT INTO `coin_dev_member` VALUES (902, 'decred', 'Jimmy Song', '创始人', 'https://s2.gongft.com/image/20190619/2111560934489511.png', 'https://twitter.com/jimmysong', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (903, 'decred', 'Dave Collins', '首席设计师', 'https://s2.gongft.com/image/20190619/5771560933594418.png', 'https://twitter.com/davecgh', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (904, 'holo', 'Arthur Brock', '联合创始人', 'https://s2.gongft.com/images/baike/0D1C88892D5EB60096C01EA28775B908.png?v=1593324786', 'https://twitter.com/artbrock', 'https://linkedin.com/in/artbrock/', 0, '');
INSERT INTO `coin_dev_member` VALUES (905, 'holo', 'Eric Harris-Braun', '联合创始人', 'https://s2.gongft.com/images/baike/6B5AD3C0DCDE1C613C0933DA4D5FFACB.png?v=1593325512', '', 'https://www.linkedin.com/in/zippy/', 0, '');
INSERT INTO `coin_dev_member` VALUES (906, 'holo', 'David Atkinson', '商务总监', 'https://s2.gongft.com/images/baike/1577F34334FB294B4B54F87805A1BC94.png?v=1593325638', '', 'https://www.linkedin.com/in/davidcatkinson/', 0, '');
INSERT INTO `coin_dev_member` VALUES (907, 'compound', 'Jake Chervinsky', 'Compound 法律顾问律师', 'https://s2.gongft.com/images/baike/63AC471D36FF068F8D8DC1D6AACD55A2.png?v=1605514157', 'https://twitter.com/jchervinsky', '', 0, '<p>Jake Chervinsky 法律顾问律师，Twitter pro，曾在 Kobre &amp; Kim &amp; Baker McKenzie 担任诉讼律师和合规律师。</p>\n');
INSERT INTO `coin_dev_member` VALUES (908, 'compound', 'Geoffrey Hayes', 'Compound 创始人兼首席技术官。', 'https://s2.gongft.com/images/baike/FED1B1955B17DDE9BF47871D11186C68.png?v=1605521534', 'https://twitter.com/justHGH', '', 0, '<p>Geoffrey Hayes 是 Compound 创始人兼首席技术官，他维护着 Exthereum，从前他是 Postmates 的工程师、Safe Shepherd 的创始人，毕业于宾夕法尼亚大学。</p>\n');
INSERT INTO `coin_dev_member` VALUES (909, 'compound', 'Antonina Norair', 'Compound 资深开发工程师', 'https://s2.gongft.com/images/baike/50D159E4CD909237FE811E1282F9F21B.png?v=1605521602', '', '', 0, '<p>Antonina Norair 现任 Compound 资深开发工程师，此前是 ConsenSys 资深开发工程师，在软件工程方面拥有十年的经验，并且支持各种不同的项目。 对区块链、DeFi、智能合约开发、创新金融科技项目颇感兴趣。</p>\n');
INSERT INTO `coin_dev_member` VALUES (910, 'compound', 'Calvin Liu', 'Compound Finance 战略主管', 'https://s2.gongft.com/images/baike/C8708C29F74A55808A97F15E6CA6DD5C.png?v=1605521652', 'https://twitter.com/cjliu49', '', 0, '<p>Calvin Liu 是 Compound Finance 战略主管，这是基于以太坊的算法货币市场协议，由 A16Z、Bain、Polychain、Coinbase 等公司支持。他也是一位活跃的加密投资者，之前在 Gusto 进行数据分析，为一些金融科技创业公司提供建议。</p>\n');
INSERT INTO `coin_dev_member` VALUES (911, 'compound', 'Jayson Hobby', 'Compound Finance 设计总监', 'https://s2.gongft.com/images/baike/1B91ABABA7E7A6E1E75AD47734700BA7.png?v=1605521858', 'https://twitter.com/jaysonhobby', '', 0, '<p>Jayson Hobby 是 Compound Finance 设计总监，也是一名多学科设计师，现居旧金山。此前，在 Coinbase、Uber、Upperquad、Fantasy 工作。</p>\n');
INSERT INTO `coin_dev_member` VALUES (912, 'compound', 'Mykel Pereira', 'Compound 软件开发工程师', 'https://s2.gongft.com/images/baike/7551107B58773A2070F57FB5647BDB9D.png?v=1605521913', 'https://twitter.com/mykelp', '', 0, '<p>Mykel Pereira 现任 Compound 软件开发工程师。此前，他是 Marble Protocol 与 Haywheel 联合创始人。他热爱技术开发、设计与美食。</p>\n');
INSERT INTO `coin_dev_member` VALUES (913, 'compound', 'Coburn Berry', 'Compound 软件开发工程师', 'https://s2.gongft.com/images/baike/B74BB2816353B8CA3F18EA960F1D4B57.png?v=1605521952', '', '', 0, '<p>Coburn Berry 是 Compound 软件开发工程师，此前是 RealReal 经验丰富的 Web 堆栈工程师，更早前是律师。他对 Elixir、iOS 开发、Swift、Phoenix 框架、Postgresql、JavaScript、Ruby on Rails、CSS、HTML5、SQL、Web 开发等经验丰富。</p>\n');
INSERT INTO `coin_dev_member` VALUES (914, 'compound', 'Torrey Atcitty', 'Compound 软件开发工程师', 'https://s2.gongft.com/images/baike/AFFFEA6E089900E6C4C53723B81CEA59.png?v=1605522134', '', '', 0, '<p>Torrey Atcitty 是 Compound 软件开发工程师，主管应用开发，曾在 Postmates、Kahuna、Aha Mobile 领导移动开发。他热衷于构建流畅体验的移动应用，并设计高度可扩展的系统，为所有类型的应用程序提供有用的服务。</p>\n');
INSERT INTO `coin_dev_member` VALUES (915, 'compound', 'Max Wolff', 'Compound 软件开发工程师', 'https://s2.gongft.com/images/baike/3BD200B1E5914190770850155A25C59F.png?v=1605522168', 'https://twitter.com/maxcwolff', '', 0, '<p>Max Wolff 是 Compound 软件开发工程师，此前，他参与创办 Marble，曾在 Mammoth Media 担任产品分析师，还在 Techstars 做过助理。他是开放式金融爱好者，毕业于斯坦福大学的经济学专业。</p>\n');
INSERT INTO `coin_dev_member` VALUES (916, 'compound', 'Adam Bavosa', 'Compound 领导开发者关系', 'https://s2.gongft.com/images/baike/758A327A99563AAF59CFF54823E5856F.png?v=1605522214', 'https://twitter.com/adambavosa', '', 0, '<p>Adam Bavosa 在 Compound 领导开发者关系，此前，也在 PubNub 负责开发者关系。他喜欢研究未来技术，喜欢组建团队和开发软件。</p>\n');
INSERT INTO `coin_dev_member` VALUES (917, 'compound', 'Jared Flatow', 'Compound 资深软件开发工程师', 'https://s2.gongft.com/images/baike/D00565ED01F63F6189926A692E0B1FB2.png?v=1605522274', 'https://twitter.com/jmflatow', '', 0, '<p>Jared Flatow 现任 Compound 资深软件开发工程师，正创建高效的区块链货币市场。 他曾创办 Quasi Convex Union，并曾在一些创业公司工作，包括开发名为 Skej 的产品。</p>\n\n<p>他出生在美国纽约州，在莱斯大学学习电气和计算机工程，在西北大学生物医学信息学中心工作，2009 年移居加州帕洛阿尔托，加入诺基亚研究中心 Data Insight 计划。</p>\n');
INSERT INTO `coin_dev_member` VALUES (918, 'oasislabs', 'Dawn Song', 'CEO', 'https://s2.gongft.com/images/baike/EB82E770101241A295760D629D833AE7.png?v=1605775689', '', '', 0, '');
INSERT INTO `coin_dev_member` VALUES (919, 'qtum', '帅初', '量子链 Qtum 创始人、BitSE 联合创始人兼首席技术官。', 'https://s2.gongft.com/images/baike/8a4f190b66b320a15ef60e9ad983fe21.jpg', 'https://twitter.com/patrickxdai', 'https://www.linkedin.com/in/patrick-dai-39278a108/', 0, '\n                            <p>帅初，原名戴旭光，量子链 Qtum 创始人，BitSE 联合创始人兼 CTO，28 岁入选 2017《福布斯》中国 30 位 30 岁以下精英榜，撰写了《从 0 到 1 建立自己的区块链》开发手册。他是中国科学院博士辍学，曾就职于阿里巴巴集团，具有丰富的区块链技术开发和管理经验，致力于推动区块链技术早日走向主流。</p>\n                            \n                        ');

SET FOREIGN_KEY_CHECKS = 1;
