/*
 Navicat Premium Data Transfer

 Source Server         : boter
 Source Server Type    : MySQL
 Source Server Version : 80030
 Source Host           : 43.128.224.150:3306
 Source Schema         : boter_dev

 Target Server Type    : MySQL
 Target Server Version : 80030
 File Encoding         : 65001

 Date: 24/09/2022 06:34:21
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for coin_dev_member
-- ----------------------------
DROP TABLE IF EXISTS `coin_dev_member`;
CREATE TABLE `coin_dev_member`  (
  `id` int(0) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'code',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'name',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'title',
  `headimg` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'headimg',
  `twitterlink` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'twitterlink',
  `linkinLink` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'linkinLink',
  `description` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'description',
  `isfounder` int(0) NOT NULL COMMENT 'isfounder',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 231 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of coin_dev_member
-- ----------------------------
INSERT INTO `coin_dev_member` VALUES (111, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (112, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (113, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (114, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (115, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (116, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (117, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (118, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (119, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (120, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (121, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (122, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (123, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (124, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (125, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (126, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (127, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (128, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (129, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (130, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (131, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (132, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (133, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (134, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (135, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (136, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (137, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (138, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (139, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (140, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (141, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (142, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (143, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (144, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (145, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (146, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (147, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (148, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (149, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (150, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (151, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (152, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (153, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (154, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (155, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (156, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (157, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (158, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (159, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (160, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (161, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (162, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (163, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (164, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (165, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (166, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (167, 'bitcoin', '中本聪', '创始人', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (168, 'bitcoin', '加文·安德烈森', '前比特币首席开发者，比特币基金会创始人', 'https://s2.gongft.com/image/20190620/9811561013213960.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (169, 'bitcoin', 'Matt Corallo', 'Bitcoin Core开发团队成员', 'https://s2.gongft.com/image/20190620/7111561014100083.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (170, 'bitcoin', 'Wladimir J. van der Laan', '比特币存储库首席维护者', 'https://s2.gongft.com/image/20190620/2971561014436567.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (171, 'bitcoin', 'Jonas Schnelli', '比特币核心开发人员和维护者', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (172, 'bitcoin', 'Luke Dash Jr', '比特币核心开发人员', 'https://s2.gongft.com/image/20190620/6771561015029713.png', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (173, 'bitcoin', 'Peter Todd', '比特币核心开发人员', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (174, 'bitcoin', 'Pieter Wuille', '比特币核心开发人员，Blockstream联合创始人兼核心开发者。', 'https://s2.gongft.com/images/baike/7ed5fa73b33ee137f309c6b8749c6bd5.jpg', '', '', '<p>Peter Wuille是比特币核心开发者，也是Blockstream联合创始人。他在提交比特币核心代码方面，排名第二，负责过比特币的重要改进，比如BIP 66，libsecp256k1、Segregated Witness 等。其擅长的编程语言，包括 C++、C、Perl、Java、Bash、(PG) SQL、Haskell、OCaml、PHP 系统管理等等。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (175, 'tether', 'Craig Sellars', '创始人兼顾问', 'https://s2.gongft.com/image/20190622/8151561175194467.png', '', 'https://www.linkedin.com/in/craigcsellars/', '', 0);
INSERT INTO `coin_dev_member` VALUES (176, 'tether', ' JL Van Der Velde', '首席执行官', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (177, 'tether', 'Giancarlo Devasini', '首席财务官', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (178, 'tether', 'Phil Potter', 'Bitfinex 与 Tether 首席战略官。', 'https://s2.gongft.com/images/baike/612647c31b17f1e13bd19ee9f9508d37.jpg', '', 'https://www.linkedin.com/in/phil-potter-0b6756154/', '\n                            <p>Phil Potter 自 1994 年毕业于耶鲁大学，曾经是摩根士丹利的衍生品交易分析师，而后开发自动化投资组合管理技术，在贝尔斯登工作两年以后，他参与创办 Mercury Securities, LLC，担任首席技术官，而后共同创立了 PacMid Technologies、Dimension Capital 等，专注于开发和实施尖端交易技术以及创建成功的自动交易咨询业务。</p>\n<p>2013 年起，他开始涉足比特币相关的项目，起初作为 Bitfinex 大客户做加密货币基金管理，后被说服于 2013 年底加入 Bitfinex，担任首席战略官。同时，他参与开发了 Tether，也担任首席战略官。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (179, 'tether', 'Matthew Tremblay', '首席合规官', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (180, 'monero', 'Riccardo Spagni', 'Monero 核心开发，项目负责人', 'https://s2.gongft.com/images/baike/fe605be47d32b8969212067fc1ddc898.jpg', 'https://twitter.com/fluffypony', '', '<p>Riccardo Spagni 是 Monero 核心团队成员，也是 Monero 项目目前的管理者、主要维护者。他具有信息学与物流的背景，早于 2011 年初开始参与比特币开发，2012 年参与到各种加密货币相关的项目开发中，并在 2017 年推出了 Globee 多币种支付处理器。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (181, 'chiliz', 'Emma Diskin', '首席运营官', 'https://s2.gongft.com/images/baike/60BF460A716B04C7F14E709EE9DB0147.png?v=1591684689', '', 'https://www.linkedin.com/in/emmalucasdiskin/', '', 0);
INSERT INTO `coin_dev_member` VALUES (182, 'chiliz', 'Max Rabinovitch', '首席战略官', 'https://s2.gongft.com/images/baike/2C355E36A597A9F58CA7BDC78B9D0A28.png?v=1591684815', '', 'https://www.linkedin.com/in/max-rabinovitch/', '', 0);
INSERT INTO `coin_dev_member` VALUES (183, 'ethereum', 'Gavin Wood', '创始人兼首席技术官', 'https://s2.gongft.com/image/20190621/4731561099774617.png', 'https://twitter.com/gavofyork', 'https://www.linkedin.com/in/gavin-wood-88843316/', '', 0);
INSERT INTO `coin_dev_member` VALUES (184, 'ethereum', 'Jeffrey Wilcke', '创始人和Go-Ethereum领导', 'https://s2.gongft.com/image/20190621/8231561099283368.png', 'https://twitter.com/jeffehh', 'https://www.linkedin.com/in/jeffreywilcke', '<p>Jeffrey Wilcke是以太坊的创始人之一。他于2013年开始使用Go编程语言首次实现以太坊，并一直担任Go团队负责人和首席开发人员。Go客户端于2015年7月30日成功推出，标志着创世块和以太坊平台的发布。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (185, 'ethereum', 'Anthony Di lorio', '创始人', 'https://s2.gongft.com/image/20190621/2281561099563578.png', 'https://twitter.com/diiorioanthony', 'https://www.linkedin.com/in/anthonydiiorio1/', '', 0);
INSERT INTO `coin_dev_member` VALUES (186, 'ethereum', 'Joseph Lubin', '创始人', 'https://s2.gongft.com/image/20190621/7931561098887167.png', 'https://twitter.com/ethereumjoseph', 'https://www.linkedin.com/in/joseph-lubin-48406489', '<p>Joseph Lubin，就职于ConsenSys，现任创始人一职。作为行业享有盛名的大咖，Joseph Lubin行事低调，对工作热情饱满，多次受邀作为嘉宾出席各类大会，并发表了精彩演讲。<br />\n2016年09月19日，Joseph Lubin受邀参加了由以太坊基金会在虹口区黄浦路199号主办的《2016上海区块链国际周(Shanghai International Blockchain Week)》，并发表了精彩演讲。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (187, 'ethereum', 'Vlad Zamfir', '以太坊开发团队的核心成员。', 'https://s2.gongft.com/images/baike/7c972b50029c452c747c8ff805e8cb1c.jpg', 'https://twitter.com/vladzamfir', 'https://www.linkedin.com/in/vlad-zamfir/', '<p>Vlad Zamfir 是以太坊开发团队的核心成员，也是博雅公关公司的数据分析顾问。他积极参与以太坊社区，工作主要聚焦于以太坊生态中的「加密经济学」、PoS 股权证明、Sharding 分片等。</p>\n\n<p>自 2014 年以来，Vlad Zamfir 一直是以太坊基金会的研究员，他是 Casper 协议升级的首席开发者。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (188, 'ethereum', 'Mihai Alisie', '以太坊、Bitcoin Magazine 联合创始人。', 'https://s2.gongft.com/images/baike/8e6708fd017360dc61c2dacf0eaebb27.jpg', 'https://twitter.com/MihaiAlisie', 'https://www.linkedin.com/in/mihaialisie/', '<p>Mihai Alisie 是以太坊、Bitcoin Magazine 的联合创始人，目前专注于使 Akasha 项目的梦想成为现实。他自 2011 年以来一直积极参与区块链技术，当时，他与 Vitalik Buterin 共同创建了世界上首个以比特币为中心的出版物 Bitcoin Magazine，由他担任该杂志的主编，直至 2013 年底，他也加入 Vitalik 创立的以太坊项目。</p>\n\n<p>在以太坊的早期，Mihai Alisie 领导瑞士创建对以太坊众筹活动至关重要的商业基础设施和法律框架。此后，他监督了以太坊的战略，和以太坊基金会副主席的工作。直到 2015 年底，他将注意力转向 AKASHA 项目。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (189, 'ethereum', 'Gustav Simonsson', '以太坊的核心开发者之一。', 'https://s2.gongft.com/images/baike/2a688fea428828654e6e19a11df10b7c.jpg', 'https://twitter.com/classygustav', '', '<p>Gustav Simonsson 为以太坊的核心开发者，具体工作涉及共识协议、核心客户端和网络安全方面，专注于以太坊区块链的安全性、Golang 客户端，确保平台的安全性。</p>\n\n<p>他拥有计算机科学背景，自 2011 年以来一直致力于开发复杂的后端系统，并在金融科技、支付处理、电信与区块链系统上积累经验。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (190, 'ethereum', 'Lane Rettig', '以太坊 Ewasm 独立开发者。', 'https://s2.gongft.com/images/baike/3746edc0a3deab4ab806b0e561783ae1.jpg', 'https://twitter.com/lrettig', '', '\n                            <p>Lane Rettig 是独立的以太坊核心开发者，也是 Ewasm 团队的成员之一，专注于为以太坊 2.0、分片等相关工作。他主要从事有关用户及开发者的体验设计、治理和社交可扩展性的独立研究。</p>\n<p>另外，他是纽约曼哈顿的加密社区 Crypto NYC 的创始人，致力于使所有人都能使用 Web 3.0 与区块链技术。他是黑客、马拉松跑者、冒险家与企业家、经济学家、思想家、作家，掌握多门语言，还是沃顿商学院 MBA 学生。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (191, 'ethereum', 'Hudson Jameson', '以太坊开发者，专注于 Solidity 编程语言。', 'https://s2.gongft.com/images/baike/93fbe60c9375abf3057fb1a577ef2dab.jpg', 'https://twitter.com/hudsonjameson', 'https://www.linkedin.com/in/hudsonjameson/', '\n                            <p>以太坊开发者，专注于 Solidity 编程语言，工作在 Oaken Innovations 与以太坊基金会。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (192, 'ethereum', 'Martin Holst Swende', '以太坊安全主管。', 'https://s2.gongft.com/images/baike/72581667eb490c51dcba1c3f7f423b5e.jpg', 'https://twitter.com/mhswende', 'https://www.linkedin.com/in/martin-holst-swende-a6664/', '<p>Martin Holst Swende，以太坊基金会安全部门主管。</p>', 0);
INSERT INTO `coin_dev_member` VALUES (193, 'ethereum', 'Jake Lang', '在以太坊核心开发与研究者，主要从事 Ewasm 开发。', 'https://s2.gongft.com/images/baike/ee7e3b8a5fbe25a315d95f845f929715.jpg', 'https://twitter.com/jake_theripper', 'https://www.linkedin.com/in/jak3lang/', '\n                            <p>Jake Lang 在以太坊，从事 Ewasm 开发，也在 etclabscore 上使用 SputnikVM JIT，亦是 Wasm-chisel 共同维护者。 他对 Rust、WebAssembly、OSDev 以及加密的所有东西都感兴趣。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (194, 'ethereum', 'Alex Beregszaszi', '以太坊开发者。', 'https://s2.gongft.com/images/baike/f927a441b4e168b7d9a80ed6378aa382.jpg', 'https://twitter.com/alexberegszaszi', 'http://ie.linkedin.com/in/alexberegszaszi', '\n                            <p>以太坊开发者，常出现在都柏林、柏林以及区块链上。更具体地说，是出现在 Solidity 与 Ewasm 上。懒得发推特，更多在 Github 上。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (195, 'ethereum', 'Mister Ligi', '以太坊开发者。', 'https://s2.gongft.com/images/baike/967645ff1234359058c78e2da35e2194.jpg', 'https://twitter.com/mr_ligi', '', '\n                            <p>Mister Ligi 是以太坊开发者。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (196, 'ethereum', 'Aya Miyaguchi', '以太坊基金会执行总监。', 'https://s2.gongft.com/images/baike/7b60ede6e6ee89fa9a9d4bded68bcafe.jpg', 'https://twitter.com/mi_ayako', 'https://www.linkedin.com/in/amiyaguchi/', '\n                            <p>Aya Miyaguchi 目前是以太坊基金会执行总监，曾在 Kraken 交易平台全权负责日本地区的运营工作。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (197, 'ethereum', 'Joey Zhou', '以太坊开发的鼻祖级人物。', 'https://s2.gongft.com/images/baike/c77980f9b5e0396f418985756ab87902.jpg', 'https://twitter.com/josephzhou', 'https://www.linkedin.com/in/josephyzhou/', '\n                            <p>Joey Zhou 是以太坊开发的鼻祖级人物，早在 2014 年，编写了以太坊上的首个节点实现，并为 Geth、Go-Ethereum、CPP-Ethereum 协议的开发做出了重要贡献。另外，他是 Cyborgenic 咨询公司的管理合伙人，专注于金融科技创新，亦是一位活跃的天使投资人和创业顾问。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (198, 'ethereum', 'Péter Szilágyi', '以太坊核心开发者。', 'https://s2.gongft.com/images/baike/78964ccd6dfea14bf93ba0bb85593659.jpg', 'https://twitter.com/peter_szilagyi', 'https://www.linkedin.com/in/karalabe/', '\n                            <p>Péter Szilágyi，代号 Karalabe，以太坊的核心开发者，另外，他也是分布式通讯应用 Project Iris 的作者、RegionRank 创始人、Ether API 共同创建者。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (199, 'ethereum', 'Greg Colvin', '号称「以太坊甘道夫」。', 'https://s2.gongft.com/images/baike/d4992988ae2587bab1fdac0a1c972396.jpg', 'https://twitter.com/greg_colvin', 'https://www.linkedin.com/in/gregcolvin/', '\n                            <p>「以太坊甘道夫」之称的工程师 Greg Colvin，现为 Algorand 项目理论团队成员，凭借三十多年的计算机软件研发经验，帮助项目创建原子交换、智能合约、虚拟机等。Colvin 拥有康奈尔大学的定量心理学博士学位，以及科罗拉多大学心理学和计算机科学学士学位，并在 ANSI/ISO c++标准委员会任职多年，在企业软件开发公司甲骨文是负责创建 Oracle Java 虚拟机的团队的主要成员，最近参与了以太坊虚拟机性能的改进，并致力于提高以太坊生态系统中流程的透明度。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (200, 'ethereum', 'Fabian Vogelsteller', 'LUKSO 创始人，以太坊项目从事 Ðapp 开发。', 'https://s2.gongft.com/images/baike/aca18a88aa777d83bbe989adc84daa59.jpg', 'https://twitter.com/feindura', 'https://www.linkedin.com/in/fabian-vogelsteller-46365042/', '<p>Fabian Vogelsteller 是 LUKSO 创始人、作者，从前在 Mist、Web3.js 以及以太坊项目从事 &ETH;app 开发。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (201, 'ethereum', 'Raul Jordan', 'Prysmatic Labs 联合创始人，以太坊开发者。', 'https://s2.gongft.com/images/baike/aaaa000ca9c606014b15771281620c77.jpg', 'https://twitter.com/raulitojordan', '', '<p>Raul Jordan 是 Prysmatic Labs 联合创始人，也兼任 zk Capital 合伙人，毕业于哈佛，区块链工程师、以太坊开发者，专注于 Prysmatic Labs 分片技术开发。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (202, 'ethereum', '平井洋一', '以太坊形式化验证工程师，负责虚拟机项目。', 'https://s2.gongft.com/images/baike/f9e61c8ac1daf0e7c646b43cb5ebffae.jpg', 'https://twitter.com/pirapira', '', '\n                            <p>以太坊形式化验证工程师，负责虚拟机项目。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (203, 'ethereum', 'Justin Drake', '以太坊的研究分析师。', 'https://s2.gongft.com/images/baike/26ab39cb5a23b8dc2dfc9a0384da8157.jpg', 'https://twitter.com/drakefjustin', 'https://www.linkedin.com/in/drakefjustin', '\n                            <p>Justin Drake 住在英国剑桥，拥有英国剑桥大学数学系学士和硕士学位。他于 2013 年创立了剑桥比特币聚会小组，并于 2014 年离开了他作为程序员、FPGA 工程师的职位，专心研究区块链领域。2015 年，他运营了比特币 ATM，并成立了 Duo Money，一家为 OpenBazaar 提供网络界面的公司。而现在，他是以太坊基金会的研究分析师，专注于分片。</p>\n<p>他在 18 岁之后定居英国剑桥，是法国人也是意大利人，妻子是俄罗斯人。父亲是一名工程师，英国人，而母亲是一名心理师，阿根廷人。可见 Justin Drake 的成长背景与生活经验十分国际化，自幼在法国长大，中学时期在中国，此后在英国。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (204, 'ethereum', 'Karl Floersch', '以太坊核心开发者。', 'https://s2.gongft.com/images/baike/7240a3cf09c18ab2ac8e145d70f59a7d.jpg', 'https://twitter.com/karl_dot_tech', 'https://www.linkedin.com/in/karlfloersch', '\n                            <p>以太坊核心开发者，年仅 23 岁，主要参与开发以太坊 Casper 以及权益证明机制 PoS 运算法则。除研究 Casper 以外，他爱好冥想和即兴饶舌，从小受到印度教的熏陶，通过冥想来思考和感悟一些事情，用饶舌表达自己当下的感受。</p>\n<p>Casper 的设计理念最初源于 Vitalik、Vlad 及其他研究者的讨论，已经归纳出的核心原则包括：关键的经济因素、必要的稳健性、普通用户的优先原则。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (205, 'ethereum-classic', 'Igor Artamonov', '创始人兼首席技术官', '', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (206, 'binance-coin', 'Roger Wang', '联合创始人兼首席技术官', 'https://s2.gongft.com/image/20190622/6611561172069411.png', '', 'https://www.linkedin.com/in/rogerlilaiwang/', '<p>Roger是联合创始人兼首席技术官。他在金融行业工作了10多年，负责组建技术团队。在BijieTech之前，Roger在日本最大的投资银行野村证券工作。他负责一个全球信用记录、分析和评分系统，该系统支持数千名全球交易员和分析师。他还成功地实现了一个智能债券匹配引擎。在野村证券(Nomura)之前，他是摩根士丹利(Morgan Stanley)的一名技术领导者。在摩根士丹利，他设计并构建了一个金融TB级别的数据仓库，支持大量用户进行实时数据分析和金融建模。他还是低延迟算法交易系统的核心开发人员，该系统为该公司最大的客户提供服务，如百仕通(Blackstone)和惠灵顿基金(Wellington Fund)，为该公司带来了可观的佣金收入。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (207, 'binance-coin', 'James Hofbauer', '首席架构师', 'https://s2.gongft.com/image/20190622/6611561173101862.png', '', 'https://www.linkedin.com/in/jamesjhofbauer/', '<p>詹姆斯（James）在美国长大并接受教育，以优异成绩获得计算机科学学士学位。他精通两种语言，英语为母语，日语流利<br />\n他设计并实现了核心匹配引擎及其中间件。他还负责监管客户端交易所的公共端点，以确保安全性和高性能。在BijieTech之前，James就职于硅谷一家专注于大数据分析的公司Palantir。在Palantir之前，James在Fusion Systems工作。James参与的一个著名项目是一家全球投资银行的系统架构重新设计，重点是减少系统数量，加密和安全地处理敏感数据，并引入了一个新的用户安全系统。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (208, 'binance-coin', 'Paul Jankunas', '工程副总裁', 'https://s2.gongft.com/image/20190622/6701561173659274.png', '', 'https://www.linkedin.com/in/paul-jankunas-4ba9513/', '<p>Paul是BijieTech的工程副总裁，负责核心机器引擎的c++实现。他拥有超过15年开发外汇系统和金融交易应用程序的经验。在BijieTech之前，Paul在东京SBI集团的SBI BITS工作。SBI集团是一家上市金融服务公司，业务范围广泛。Paul负责交易应用程序的客户端和服务器端开发。在此之前，Paul曾在东京的fsystems工作，担任猛禽(Raptor)的开发主管。猛禽是一种延迟小于2微秒的市场门户，此前他在纽约为彭博社(Bloomberg)工作。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (209, 'binance-coin', 'Allan Yan', '产品总监', 'https://s2.gongft.com/image/20190622/5121561174220099.png', '', 'https://www.linkedin.com/in/allannyan/', '<p>Allan是BijieTech的联合创始人和产品总监。Allan拥有超过10年的产品设计、用户体验和贸易经验。他推动BijieTech建立的交换系统的创新，并推动产品在这个竞争激烈的领域远远领先于竞争对手。在BijieTech之前，Allan就职于东方国际控股有限公司，这是上海最大的进出口公司之一。负责ERP、e-Fax等多个信息化产品的实施。同时，他还领导了各种游戏和视频点播内容平台。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (210, 'binance-coin', 'Sunny Li', '运营总监', 'https://s2.gongft.com/image/20190622/4801561174521281.png', '', 'http://www.linkedin.com/in/SunnyJiachenLi', '<p>Sunny是BijieTech的联合创始人和运营总监。他拥有多年的管理和技术咨询经验，领导过20多个交流系统项目，为战略、运营、风险控制和系统开发提供全面咨询。<br />\n在BijieTech之前，Sunny在埃森哲担任高级顾问。为多家世界500强企业提供战略咨询和IT咨询服务，主持多项物联网、大数据、ERP信息集成系统项目。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (211, 'ripple', 'Brad Garlinghouse', 'Ripple 首席执行官。', 'https://s2.gongft.com/images/baike/ec2586d02e1ebe75507644dbf0247150.jpg', 'https://twitter.com/bgarlinghouse', 'https://www.linkedin.com/in/bradgarlinghouse/', '\n                            <p>Brad Garlinghouse 是 Ripple 首席执行官，也是董事会成员。在加入 Ripple 之前，他曾担任文件协作服务 Hightail 的首席执行官、美国在线 AOL 消费者应用总裁，以及在雅虎担任过多个行政职位。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (212, 'ripple', 'Ed Roman', 'Hack VC 管理合伙人。', 'https://s2.gongft.com/images/baike/e284298d4e00fc4854e53bf094ac2f18.jpg', 'https://twitter.com/ed_roman', 'https://www.linkedin.com/in/ed-roman-19686/', '\n                            <p>Ed Roman 是 Hack VC 管理合伙人、企业家、开发者，以及天使投资人。他的专长是发展小企业，组建和领导团队取得成功。另外，他也是一位屡获殊荣的游戏开发者、畅销的技术书籍作者。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (213, 'ripple', 'Chris Larsen', 'Ripple 联合创始人、执行主席。', 'https://s2.gongft.com/images/baike/d3f70a3d03c7d7dd4be16536b4f01d89.jpg', 'https://twitter.com/chrislarsensf', 'https://www.linkedin.com/in/chris-larsen-7721772/', '\n                            <p>Chris Larsen 是 Ripple 联合创始人兼执行主席，Ripple 是一家全球支付的企业区块链解决方案。他目前是数据科学公司 Distilled Analytics 的顾问。 在创立 Ripple 之前，他是 P2P 贷款服务公司 Prosper 的首席执行官，也是在线贷款服务公司 E-LOAN 的首席执行官。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (214, 'ripple', 'David Schwartz', '首席技术官', 'https://s2.gongft.com/image/20190621/9111561104168747.png', 'https://twitter.com/JoelKatz', 'https://www.linkedin.com/in/david-schwartz-8b767b34/', '<p>David Schwartz是Ripple的首席技术官，是Ripple共识网络的原始架构师之一。在加入Ripple之前，David Schwartz是Santa Clara软件开发人员WebMaster Incorporated的首席技术官。他为CNN和国家安全局（NSA）等组织开发了加密云存储和企业消息系统。被称为&ldquo;JoelKatz&rdquo;，他是数字货币界的一位受人尊敬的代言人。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (215, 'ripple', 'Asheesh Birla', '产品副总裁', 'https://s2.gongft.com/image/20190621/2061561104435973.png', 'https://twitter.com/ashgoblue', 'https://www.linkedin.com/in/asheeshbirla/', '<p>在2013年首次加入领导其产品套件的开发。Asheesh是区块链行业专家，是区块链和加密货币的撰稿人，演讲者和顾问。Asheesh 15年前在硅谷开始了他的企业家生涯，他在那里创立了一家内容管理公司，并于2005年将其出售给Thomson-Reuters，成为他们的全球技术副总裁。2010年离开Thomson-Reuters之后，Asheesh建议并在硅谷的一些初创公司领导产品设计。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (216, 'ripple', 'Patrick Griffin ', '业务发展高级副总裁', 'https://s2.gongft.com/image/20190621/5711561104782708.png', 'https://twitter.com/patgriffin9', 'https://www.linkedin.com/in/patrick-griffin-72b1255', '<p>在加入Ripple之前是互联网支付和身份公司Jumio的早期雇员，负责构建业务开发团队和销售策略。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (217, 'ripple', 'Christopher Kanaan', '工程副总裁', 'https://s2.gongft.com/image/20190621/2731561104957226.png', '', 'https://www.linkedin.com/in/ckanaan/', '', 0);
INSERT INTO `coin_dev_member` VALUES (218, 'ripple', 'John Mitchell', '高级副总裁', 'https://s2.gongft.com/image/20190621/6591561105935820.png', '', 'https://www.linkedin.com/in/johnemitchell/', '<p>Eric van Miltenburg是Ripple的业务运营高级副总裁。他在业务开发，战略规划，业务运营和企业发展方面拥有20年的领导经验。在加入Ripple之前，曾在高增长的初创企业和财富500强企业担任高级职位，包括Adobe，Yahoo！，Hightail，RedSwoosh，Work.com和Excite@Home.com。他以解决复杂业务问题和执行有助于技术公司加速增长战略的丰富经验而闻名。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (219, 'ripple', 'Brynly Llyr', '总法律顾问', 'https://s2.gongft.com/image/20190621/7391561105612855.png', '', 'https://www.linkedin.com/in/brynly-llyr-3075709/', '<p>Brynly Llyr是Ripple的总法律顾问。在加入Ripple之前，为金融科技公司提供法律服务，并担任高级法律顾问职务，包括担任PayPal中小企业集团的法律总顾问以及eBay的诉讼高级总监。在这些职位上，她领导诉讼团队，就商业交易，并购和知识产权保护等问题开展合作。Brynly Llyr还曾在O&#39;Melveny＆Myers和Charles Schwab担任过职务，并在美国加利福尼亚州北区地方法院的Fern M. Smith（Ret。）法官下任职。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (220, 'ripple', 'Monica Long ', '营销副总裁', 'https://s2.gongft.com/image/20190621/3931561105806130.png', 'https://twitter.com/MonicaLongSF', 'https://www.linkedin.com/in/monicalong/', '<p>onica Long是Ripple的市场营销和传播高级副总裁。在她的职业生涯中，帮助技术公司推动了金融业的根本变革。在加入Ripple之前，Monica Long曾在Intuit的企业传播部门工作。在此之前，她支持各种B2B和B2C领域的初创客户，其中有几家涉及金融科技方面，包括Prosper。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (221, 'ripple', 'Sandi Kochhar', '人力副总裁', 'https://s2.gongft.com/image/20190621/6571561105189610.png', '', 'https://www.linkedin.com/in/sandikochhar/', '<p>在加入Ripple之前，她曾在AppDirect，Atlassian和SuccessFactors等企业软件公司担任多个领导职务。在每个角色中，她帮助公司扩展规模，领导全球扩张，并购整合以及与IPO相关的活动。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (222, 'ripple', 'Catherine Coley', '在 Ripple 负责 XRP 机构流动性的主管。', 'https://s2.gongft.com/images/baike/8a807eac7bae786aeee73be864dffccd.jpg', 'https://twitter.com/cryptocoley', 'https://www.linkedin.com/in/catherinegcoley/', '\n                            <p>Catherine Coley 在 Ripple 主管 XRP 机构流动性，此前，她在硅谷银行为初创企业的全球支付与战略扩张提供建议，以前她也有与摩根士丹利的香港、伦敦分部进行外汇交易市场的经验，与全球对冲基金和资产管理公司密切合作。她是香港中文大学、哥本哈根商学院、北卡罗来纳 Kenan Flagler 商学院的全球学者。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (223, 'cardano', 'Charles Hoskinson', '创始人', 'https://s2.gongft.com/image/20190622/2981561188085146.png', 'https://twitter.com/IOHK_Charles', 'https://www.linkedin.com/in/charles-hoskinson-1a95a4b4/', '<p>查尔斯&middot;霍金森(Charles Hoskinson)是科罗拉多州的一位科技企业家、数学家和区块链爱好者。他主要以创造Cardano而闻名。<br />\n霍金森的专业经验包括创建三家与加密货币相关的初创企业:Invictus Innovations、Ethereum和IOHK。他还是比特币基金会教育委员会的创始主席，并于2013年9月成立了加密货币研究小组。<br />\n他目前的项目集中在加密货币主题的教育、分散化的福音传播和使主流更容易使用加密工具。</p>\n', 0);
INSERT INTO `coin_dev_member` VALUES (224, 'cardano', 'Jeremy Wood', '创始人', 'https://s2.gongft.com/image/20190622/0491561188615908.png', 'https://twitter.com/iohk_jeremy', 'https://jp.linkedin.com/in/jeremykwood', '', 0);
INSERT INTO `coin_dev_member` VALUES (225, 'cardano', 'Eileen Fitzgerald', '执行副总裁 计划负责人、COO', 'https://s2.gongft.com/image/20190622/0001561188879628.png', 'https://twitter.com/EileenFitzy', 'https://www.linkedin.com/in/eifitzgerald/', '', 0);
INSERT INTO `coin_dev_member` VALUES (226, 'cardano', 'Domen Kožar', 'CTO', '', '', 'https://www.linkedin.com/in/domen-ko%C5%BEar-b753779', '', 0);
INSERT INTO `coin_dev_member` VALUES (227, 'solana', 'Anatoly Yakovenko', 'CEO', 'https://s2.gongft.com/images/baike/4E04CEDF5E46EFBF5AAB09965FAEE905.png?v=1592812802', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (228, 'solana', 'Greg Fitzgerald', 'CTO', 'https://s2.gongft.com/images/baike/71334DBF0ED45DE1658BD33A49C7A2DD.png?v=1592812867', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (229, 'solana', 'Raj Gokal', 'COO', 'https://s2.gongft.com/images/baike/D55E383950875380247BEECC1E7DCC62.png?v=1592812957', '', '', '', 0);
INSERT INTO `coin_dev_member` VALUES (230, 'dogecoin', 'Jackson Palmer', '狗币创始人。', 'https://s2.gongft.com/images/baike/5c99f3816ea4eab8415c5b5a23808a94.jpg', 'https://twitter.com/ummjackson', 'https://www.linkedin.com/in/jacksonpalmer/', '\n                            <p>狗币创始人，也是 Adobe 高级经理。</p>\n                            \n                        ', 0);
INSERT INTO `coin_dev_member` VALUES (231, 'shibainu', 'Ryoshi', 'SHIB 和 LEASH 创始人', 'https://s2.gongft.com/images/baike/56001D79B34A146CF666CBD86DDCC91B.png?v=1620463765', 'https://twitter.com/RyoshiResearch', '', '<p>加密货币独立交易员，热衷于去中心化组织的建设与发展。</p>\n', 0);

SET FOREIGN_KEY_CHECKS = 1;
